### ISSUE TITLE
gz-sim: gpu_lidar_sensor.sdf

### ISSUE THREAD

**Issue by Voldivh** [gazebosim/gazebo_test_cases#1033]
## Setup
- Os: MacOS
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/gpu_lidar_sensor.sdf)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
LGTM, the `VisualizeLidar` plugin is not active, maybe we can add it to visualize the rays inside Gazebo
