### ISSUE TITLE
docs: hotkeys

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#11]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/hotkeys)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/hotkeys.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by mjcarroll** [comment]
Pressing `r` to rotate and `t` to translate, and 'shift' don't seem to have any visual effect on my system until you click again in the 3d window.

**Comment by Voldivh** [comment]
Closing this since Issue have been created.
