### ISSUE TITLE
gz-plugin: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#133]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/libs/plugin)
- [Source](https://github.com/gazebosim/gz-plugin/blob/gz-plugin2/README.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Bi0T1N** [comment]
Besides the changes from the linked PR, it's fine for me.

**Comment by Voldivh** [comment]
Thanks @Bi0T1N, let's wait on the PR before closing this issue.
