### ISSUE TITLE
gz-rendering: Bounding Box camera

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#137]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/rendering/8/boundingbox_camera.html)
- [Source](https://github.com/gazebosim/gz-rendering/tree/gz-rendering8/tutorials/24_boundingbox_camera_tutorial.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by iche033** [comment]
https://github.com/gazebosim/gz-rendering/pull/896
