### ISSUE TITLE
docs: install_osx_src

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#14]
## Setup
- Os: MacOS
- BuildType: Source

## Links
- [Live](https://gazebosim.org/docs/harmonic/install_osx_src)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/install_osx_src.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by srmainwaring** [comment]
### Status

- [x] Instructions work
- [x] Images (if there are any) match the result

### System

- MacBook Pro 2021, Apple M1 Max, 32 GB
- macOS Ventura 13.4
- Xcode 14.3.1 

### Details

Continuing from

- https://github.com/gazebosim/gazebo_test_cases/issues/804#issuecomment-1718954631

Run

```bash
gz sim -v4 -s -r shapes.sdf
```

```bash
gz sim -v4 -g
```

<img width="1112" alt="Screenshot 2023-09-14 at 09 27 55" src="https://github.com/gazebosim/gazebo_test_cases/assets/24916364/5d7ac511-0d2a-4a0f-ad78-02b82f10ea5f">

**Comment by Voldivh** [comment]
Thanks @srmainwaring
