### ISSUE TITLE
gz-rendering: Creating and using light maps

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#141]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/rendering/8/lightmap.html)
- [Source](https://github.com/gazebosim/gz-rendering/tree/gz-rendering8/tutorials/04_lightmap.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by iche033** [comment]
updated [Indoor Lightmap](https://app.gazebosim.org/OpenRobotics/fuel/models/Indoor%20lightmap)'s model.sdf on fuel to remove the `fuel.ignitionrobotics.org` url in texture and mesh file paths and that sped up loading the model
