### ISSUE TITLE
gz-rendering: Custom scene viewer

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#143]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/rendering/8/custom_scene_viewer.html)
- [Source](https://github.com/gazebosim/gz-rendering/tree/gz-rendering8/tutorials/13_custom_scene_viewer.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by iche033** [comment]
https://github.com/gazebosim/gz-rendering/pull/895
