### ISSUE TITLE
docs: install_ubuntu

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#15]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/install_ubuntu)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/install_ubuntu.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by suresh-venkate** [comment]
Confirming that the binary installation instructions worked fine for me.

Setup
--------
Os: Ubuntu Jammy
Build Type: Binary

Links Used
------------
[https://gazebosim.org/docs/harmonic/install_ubuntu](url)

![image](https://github.com/gazebosim/gazebo_test_cases/assets/76463566/d3147dab-ed3e-4293-9352-be2dc881874b)

![image](https://github.com/gazebosim/gazebo_test_cases/assets/76463566/c47a944f-ce00-4a87-8498-e07fc966375c)

**Comment by Voldivh** [comment]
Thanks for addressing this @suresh-venkate closing this issue as completed.
