### ISSUE TITLE
gz-sim: acoustic_comms.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1578]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/acoustic_comms.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
![Screenshot from 2024-08-31 19-48-48](https://github.com/user-attachments/assets/8014a44f-2bf2-470a-9d93-291c7ac04e7e)

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
![Screenshot from 2024-08-31 19-49-49](https://github.com/user-attachments/assets/d91366db-ab47-4258-ba77-5df7dfcd2786)

**Comment by ahcorde** [comment]
thank you for testing!
