### ISSUE TITLE
gz-sim: acoustic_comms_demo.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1579]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/acoustic_comms_demo.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
![Screenshot from 2024-08-31 19-59-42](https://github.com/user-attachments/assets/a86cc0d1-c104-476c-951a-4bf671f92fc5)
[Screencast from 08-31-2024 08:00:27 PM.webm](https://github.com/user-attachments/assets/fe2b96d2-f10a-4794-afa8-824b46bab79a)

**Comment by arjo129** [comment]
Thanks!
