### ISSUE TITLE
gz-sim: acoustic_comms_moving_targets.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1580]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/acoustic_comms_moving_targets.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-31-2024 07:41:33 PM.webm](https://github.com/user-attachments/assets/b5a7cc95-f1c9-461a-bc1a-a0d6c2913b6a)

**Comment by ahcorde** [comment]
Thank you for testing!
