### ISSUE TITLE
gz-sim: actor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1583]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/actor.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-31-2024 04:21:53 PM.webm](https://github.com/user-attachments/assets/e42c6701-e808-4a24-9372-0e5d3c85fa7a)

**Comment by ahcorde** [comment]
Thank you for testing!
