### ISSUE TITLE
gz-sim: actor_crowd.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1584]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/actor_crowd.sdf)

**Comment by akky20** [comment]
## Works fine 
[Screencast from 01-09-24 02:12:23 AM IST.webm](https://github.com/user-attachments/assets/314f3cc8-da61-4838-8994-a2fc840aacce)

**Comment by ahcorde** [comment]
Thank you for testing!
