### ISSUE TITLE
gz-sim: actors_population.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1585]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/actors_population.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
the source file is empty

**Comment by ahcorde** [comment]
PR https://github.com/gazebosim/gz-sim/pull/2581
