### ISSUE TITLE
gz-sim: advanced_lift_drag_system.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1586]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/advanced_lift_drag_system.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-31-2024 04:48:47 PM.webm](https://github.com/user-attachments/assets/018ef19b-a2af-4c7d-9931-66d95ebfd7dc)

**Comment by arjo129** [comment]
Thanks for testing!
