### ISSUE TITLE
gz-sim: apply_joint_force.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1587]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/apply_joint_force.sdf)

**Comment by avanmalleghem** [comment]
I would like to test the tutorial contained in the issue.

**Comment by avanmalleghem** [comment]
Commands
`gz topic -t "/model/joint_force_example/joint/j1/cmd_force" -m gz.msgs.Double  -p "data: 0.001"`
`gz topic -t "/model/joint_force_example/joint/j1/cmd_force" -m gz.msgs.Double  -p "data: 0.0"`
Work as expected

There is no images so this issue can be closed.
