### ISSUE TITLE
gz-sim: apply_link_wrench.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1588]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/apply_link_wrench.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
It works as expected ! Can be closed :+1:

**Comment by ahcorde** [comment]
Thank you for testing!
