### ISSUE TITLE
gz-sim: auto_inertia_pendulum.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1589]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/auto_inertia_pendulum.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-31-2024 02:18:06 PM.webm](https://github.com/user-attachments/assets/e2f5c615-9f8e-450b-9c12-386b0812470f)

**Comment by ahcorde** [comment]
Thank you for testing!
