### ISSUE TITLE
gz-sim: auto_inertia_rolling_shapes.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1590]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/auto_inertia_rolling_shapes.sdf)

**Comment by bperseghetti** [comment]
I'm available to test.

**Comment by akky20** [comment]
## Works fine

[Screencast from 01-09-24 02:08:26 AM IST.webm](https://github.com/user-attachments/assets/76073c4a-6878-4d96-980c-5e4be7dcb0dc)

**Comment by ahcorde** [comment]
Thank you for testing!
