### ISSUE TITLE
gz-sim: auv_controls.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1591]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/auv_controls.sdf)

**Comment by Combuster54** [comment]
Interested

**Comment by Combuster54** [comment]
## Ubuntu 24.04 Noble

As I mention in https://github.com/gazebosim/gazebo_test_cases/issues/1305

**Error**

```bash
combuster@combuster54:~$ gz sim auv_controls.sdf
(2024-09-02 16:11:32.239) [error] The use of added mass through this plugin is deprecated and willbe removed in Gazebo J* as this formulation has instabilities. We recommend using the SDF `<fluid_added_mass>` tag based method[http://sdformat.org/spec?ver=1.11&elem=link#inertial_fluid_added_mass]To get rid of this warning we recommend setting`<disable_added_mass> to true.
```.
**1. Move the rudder**

**2. Propel the vehicle**

gz topic -t /model/tethys/joint/propeller_joint/cmd_thrust
      -m gz.msgs.Double -p 'data: -31'

**Comment by Combuster54** [comment]
**1. Move the rudder**
![Screencast from 2024-09-02 16-15-22](https://github.com/user-attachments/assets/a3e5ac3f-86d6-459e-8690-c2d340fedbaf)

**2. Propel the vehicle**
![Screencast from 2024-09-02 16-17-36](https://github.com/user-attachments/assets/b4d9220a-d085-452d-9981-621103d8433b)

**Comment by arjo129** [comment]
> ## Ubuntu 24.04 Noble
> 
> As I mention in #1305
> 
> **Error**
> 
> ```shell
> combuster@combuster54:~$ gz sim auv_controls.sdf
> (2024-09-02 16:11:32.239) [error] The use of added mass through this plugin is deprecated and willbe removed in Gazebo J* as this formulation has instabilities. We recommend using the SDF `<fluid_added_mass>` tag based method[http://sdformat.org/spec?ver=1.11&elem=link#inertial_fluid_added_mass]To get rid of this warning we recommend setting`<disable_added_mass> to true.
> ```.
> ```

Error has been solved! Thanks for testing.
