### ISSUE TITLE
gz-sim: breadcrumbs.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1593]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/breadcrumbs.sdf)

**Comment by akky20** [comment]
## For me no error is there , Works fine 

[Screencast from 02-09-24 11:53:08 PM IST.webm](https://github.com/user-attachments/assets/a2749458-c7d7-4146-8697-c2a9f07e2cf8)

**Comment by iche033** [comment]
I can reproduce the issue with `[error] Failed to make breadcrumb 'B2_0' static.`, will look into it

**Comment by iche033** [comment]
https://github.com/gazebosim/gz-sim/pull/2593
