### ISSUE TITLE
gz-sim: buoyancy.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1594]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/buoyancy.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by akky20** [comment]
## Here is Demo , no issues
[Screencast from 01-09-24 02:02:07 AM IST.webm](https://github.com/user-attachments/assets/77812daf-c488-48d2-8ed9-3164a07fe991)

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-31-2024 11:52:57 PM.webm](https://github.com/user-attachments/assets/d6db5929-591a-477c-bbd9-5a5bcf2a087b)

**Comment by ahcorde** [comment]
Thank you for testing!
