### ISSUE TITLE
gz-sim: buoyancy_engine.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1595]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/buoyancy_engine.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy)
[Screencast from 08-31-2024 06:28:01 PM.webm](https://github.com/user-attachments/assets/c90d55d4-bf96-4825-b93b-29aa16e55804)
[Screencast from 08-31-2024 06:29:50 PM.webm](https://github.com/user-attachments/assets/66e0e975-3b40-4f86-aee7-31118b5dd244)
![Screenshot from 2024-08-31 18-31-44](https://github.com/user-attachments/assets/689c36f1-d8be-4e48-93ba-8039865fc5c9)

**Comment by ahcorde** [comment]
Thank you for testing!
