### ISSUE TITLE
gz-sim: camera_lens_flare.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1596]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/camera_lens_flare.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
![Screenshot from 2024-08-30 23-36-12](https://github.com/user-attachments/assets/ffedd873-9ce4-4d49-bd65-35f6423fc763)
![Screenshot from 2024-08-30 23-36-22](https://github.com/user-attachments/assets/926c661b-9741-4248-a936-46d842b434c8)

but this is the terminal logging
![Screenshot from 2024-08-30 23-38-48](https://github.com/user-attachments/assets/48147c5f-a824-4a30-9a8c-855997ee6c76)

**Comment by iche033** [comment]
created https://github.com/gazebosim/gz-sim/pull/2559 to fix the issue.

**Comment by khshmt** [comment]
> created [gazebosim/gz-sim#2559](https://github.com/gazebosim/gz-sim/pull/2559) to fix the issue.

It Works fine now
![Screenshot from 2024-08-31 13-20-47](https://github.com/user-attachments/assets/2298a207-6cb4-4cc1-bdc8-4648aaac51ea)

**Comment by ahcorde** [comment]
Thank you for testing! and for the fix @iche033 !
