### ISSUE TITLE
gz-sim: camera_sensor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1597]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/camera_sensor.sdf)

**Comment by Mechazo11** [comment]
Interested

**Comment by Mechazo11** [comment]
* **Test enviornment**
    ```text
    CPU: Ryzen 5 5600x, Ram: 32GB @ 3200 Mhz, GPU: RTX 3080
    Clean copy of Ubuntu 24.04 Humble
    ROS 2 Jazzy Jalisco Full Desktop 
    ```
* **Summary**
    * ```camera_sensor.sdf``` works without any errors or failures. Widget shows in bottom right corner. See video.

https://github.com/user-attachments/assets/9148e0d0-25c4-4ee6-8362-fd7821f10c38

* **Issues**
    * N/A
    
* **Fixes**
    * N/A

* **Comments/Suggestions**
    * N/A

**Comment by ahcorde** [comment]
Thank you for testing!
