### ISSUE TITLE
gz-sim: camera_video_record_dbl_pendulum.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1598]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/camera_video_record_dbl_pendulum.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##

This the saved video from running the sdf.
https://github.com/user-attachments/assets/739a43ba-0575-41a1-a705-4941de327d29

**Comment by khshmt** [comment]
[Screencast from 08-31-2024 03:59:53 PM.webm](https://github.com/user-attachments/assets/2d9e58a4-7ae6-412e-a815-a3f596aa85f2)

**Comment by ahcorde** [comment]
Thank you for testing!
