### ISSUE TITLE
gz-sim: collada_world_exporter.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1599]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/collada_world_exporter.sdf)

**Comment by akky20** [comment]
## Successfully creating collada file , here is the images for reference

![image](https://github.com/user-attachments/assets/3d3d3fa8-5e03-4b61-98aa-a21050c45896)
![image](https://github.com/user-attachments/assets/18e87290-ec11-4fc2-a7bf-c5fad9bd9002)

**Comment by ahcorde** [comment]
Thank you for testing!
