### ISSUE TITLE
docs: install_ubuntu_src

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#16]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/docs/harmonic/install_ubuntu_src)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/install_ubuntu_src.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by AndrejOrsula** [comment]
These instructions worked for me within a custom Docker image based on `ubuntu:jammy` (disabled tests).
I skipped the part about [QML Debugging](https://github.com/gazebosim/docs/blob/ed4782486aaa2ee817dc36595bc5b075acf2b9fa/harmonic/install_ubuntu_src.md#qml-debugging).

**Comment by Voldivh** [comment]
Thanks @AndrejOrsula I'll be closing this as instructions work.
