### ISSUE TITLE
gz-sim: contact_sensor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1600]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/contact_sensor.sdf)

**Comment by Combuster54** [comment]
Interested

**Comment by akky20** [comment]
### Hello I have done this please check 

## Before Simulation
![image](https://github.com/user-attachments/assets/e60e52ac-3279-4cf7-9ce7-188de2c129c2)

## After Simulation
![image](https://github.com/user-attachments/assets/1f440d73-e176-47ad-afec-2a78900e033f)

When running the topic
![image](https://github.com/user-attachments/assets/45953c5a-a4d5-445e-bd25-c0ee9b9e4cf4)

**Comment by ahcorde** [comment]
Thank you for testing!
