### ISSUE TITLE
gz-sim: debug_shapes.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1602]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/debug_shapes.sdf)

**Comment by bperseghetti** [comment]
I'm available to test.

**Comment by david-dorf** [comment]
[Screencast from 2024-08-31 15-03-26.webm](https://github.com/user-attachments/assets/008b2726-f0f3-497b-92c4-5e4b2d9d09f5)
LGTM

**Comment by ahcorde** [comment]
Thank you for testing!
