### ISSUE TITLE
gz-sim: default.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1603]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/default.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Default Configuration

![default_conf](https://github.com/user-attachments/assets/c35a40c2-8bdf-4d09-908e-43426022c7e8)

**Comment by azeey** [comment]
Thank you!
