### ISSUE TITLE
gz-sim: dem_monterey_bay.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1604]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/dem_monterey_bay.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
![Screenshot from 2024-08-31 14-10-51](https://github.com/user-attachments/assets/32a7f05f-e306-4559-ae60-29609bcb4f78)
![Screenshot from 2024-08-31 14-11-25](https://github.com/user-attachments/assets/36910958-f7c9-489c-94c2-c472537949f8)

**Comment by david-dorf** [comment]
Encountered the same issue with Ogre

**Comment by azeey** [comment]
Fix in https://github.com/gazebosim/gz-gui/pull/642
