### ISSUE TITLE
gz-sim: dem_volcano.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1606]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/dem_volcano.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-30-2024 11:13:35 PM.webm](https://github.com/user-attachments/assets/b12db3ac-4615-4b51-807b-04009f4e890d)
