### ISSUE TITLE
gz-sim: depth_camera_sensor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1607]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/depth_camera_sensor.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-30-2024 10:47:36 PM.webm](https://github.com/user-attachments/assets/2faddc04-827f-426a-94ea-e63e3bbb4b1d)
