### ISSUE TITLE
gz-sim: detachable_joint.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1608]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/detachable_joint.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by akky20** [comment]
## I have tested and has no issues 
[Screencast from 01-09-24 01:44:04 AM IST.webm](https://github.com/user-attachments/assets/d346a095-cebc-4bdb-ab45-b4849975312a)
also for the state it give the message if attached or not , unfortunatly I'm not able to record it but you can see it in terminal

**Comment by avanmalleghem** [comment]
@akky20 please avoid doing it before saying you are interested in... So that we don't do the job twice...

**Comment by arjo129** [comment]
Thanks for testing!
