### ISSUE TITLE
gz-sim: dvl_world.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1611]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/dvl_world.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-30-2024 10:15:00 PM.webm](https://github.com/user-attachments/assets/de94244d-e4d7-4a91-bbe3-01518469a82d)
