### ISSUE TITLE
gz-sim: empty.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1613]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/empty.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
Every instructions in the sdf files are working ! Example of the "new_name" with the "spawned_light"
![image](https://github.com/user-attachments/assets/4aca6fd0-9f54-4d0e-b951-bbbb6991d707)

Can be closed IMHO
