### ISSUE TITLE
gz-sim: environmental_sensor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1615]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/environmental_sensor.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
![Screenshot from 2024-08-30 21-58-13](https://github.com/user-attachments/assets/83a4229c-faa4-4864-ac1e-68518e77e3e7)
