### ISSUE TITLE
gz-sim: fluid_added_mass.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1616]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/fluid_added_mass.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-30-2024 09:50:37 PM.webm](https://github.com/user-attachments/assets/96105299-cdef-40c3-95c7-88645c6410c7)
