### ISSUE TITLE
gz-sim: follow_actor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1617]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/follow_actor.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-30-2024 09:47:32 PM.webm](https://github.com/user-attachments/assets/e5cefa24-eddf-4682-a10b-f91a754cf327)
