### ISSUE TITLE
gz-sim: fuel.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1618]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/fuel.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
![Screenshot from 2024-08-30 21-34-13](https://github.com/user-attachments/assets/423a1ac0-0e70-4d07-9436-fc6b1a8862ea)
![Screenshot from 2024-08-30 21-34-32](https://github.com/user-attachments/assets/3caa21f7-3503-49ea-881b-476b189d5153)

**Comment by khshmt** [comment]
[Screencast from 08-30-2024 09:36:35 PM.webm](https://github.com/user-attachments/assets/98855d8c-8d16-49eb-bf6f-6419da7de2bb)

**Comment by ahcorde** [comment]
Thank you for testing!
