### ISSUE TITLE
gz-sim: fuel_textured_mesh.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1619]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/fuel_textured_mesh.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Gazebo Fuel PBR Material Demo 

![phy_text_init](https://github.com/user-attachments/assets/29c9310f-0a89-497d-89a0-cd9df3fbc1d1)

### Gazebo Fuel PBR Material Demo Play

![phy_tex_play](https://github.com/user-attachments/assets/b4fd7abd-85f9-4e9e-ad15-60fc8398bbcc)
