### ISSUE TITLE
gz-sim: gpu_lidar_retro_values_sensor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1620]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/gpu_lidar_retro_values_sensor.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 2.04 (jammy) ##
![Screenshot from 2024-08-30 21-29-46](https://github.com/user-attachments/assets/691e4090-9d5e-4845-b867-711ac7c2c720)

**Comment by ahcorde** [comment]
Thank you for testing!
