### ISSUE TITLE
gz-sim: graded_buoyancy.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1622]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/graded_buoyancy.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Gazebo Buoyancy Plugin Demo

![bouyancy_init](https://github.com/user-attachments/assets/ab9aeeba-5133-4aa0-8a4c-cc4190ebf5a5)

### Gazebo Buoyancy Plugin Demo Play

![bouyancy_play](https://github.com/user-attachments/assets/780acdf5-b862-4705-8283-171f92397fc1)
