### ISSUE TITLE
gz-sim: grid.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1623]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/grid.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy)
![Screenshot from 2024-08-30 20-45-06](https://github.com/user-attachments/assets/e1918d80-6f60-442b-96ba-9138f6fa403e)
