### ISSUE TITLE
gz-sim: ground_spacecraft_testbed.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1624]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/ground_spacecraft_testbed.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
![Screenshot from 2024-08-30 20-45-06](https://github.com/user-attachments/assets/21007e6c-2e1c-4284-8cb1-4303e9e0a82d)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
the space craft does not move.
![Screenshot from 2024-08-31 18-19-25](https://github.com/user-attachments/assets/63e99669-fd30-4afc-8e60-186fcddeca41)

**Comment by Mechazo11** [comment]
* **Test enviornment**
    ```text
    CPU: Ryzen 5 5600x, Ram: 32GB @ 3200 Mhz, GPU: RTX 3080
    Clean copy of Ubuntu 24.04 Humble
    ROS 2 Jazzy Jalisco Full Desktop 
    ```
* **Summary**
    * ```ground_spacecraft_testbed.sdf``` opens correctly but the tutorial had wrong thrust command. Changed command to the correct one. Opened a PR request. The robot moves correctly as shown below

https://github.com/user-attachments/assets/7c37e46d-62a3-4c9f-bb58-1ba6502d93af

* **Issues**
    * Ground robot does not move with the given command.
    
* **Fixes**
    * ```gz topic -p 'normalized:[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]' -t /kth_freeflyer/command/duty_cycle --msgtype gz.msgs.Actuators```
    
    * See PR request [#2565](https://github.com/gazebosim/gz-sim/pull/2565)

* **Comments/Suggestions**
    * N/A

**Comment by arjo129** [comment]
Thanks for fixing the docs @Mechazo11. Closing as we have merged the fix.
