### ISSUE TITLE
gz-sim: heightmap.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1625]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/heightmap.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-30-2024 08:28:56 PM.webm](https://github.com/user-attachments/assets/55a3090b-8b50-4153-8f50-a45ae8607f53)
