### ISSUE TITLE
gz-sim: import_mesh.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1626]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/import_mesh.sdf)

**Comment by alesof** [comment]
## Configuration
Running on Ubuntu 22.04 using the suggested docker setup. Gazebo version is 9.0.0~pre1.

## Process
Step1: Instructions works and mesh is correctly imported.
![mesh_import](https://github.com/user-attachments/assets/85429c00-e4c3-421c-a22c-51cdb42de957)
