### ISSUE TITLE
gz-sim: joint_controller.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1627]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/joint_controller.sdf)

**Comment by bperseghetti** [comment]
I'm available to test.

**Comment by akky20** [comment]
## NO Issues , I have attached some images for reference 
![image](https://github.com/user-attachments/assets/1568c561-0f96-4791-b4d2-f028d494706e)
![image](https://github.com/user-attachments/assets/4aff5a50-de55-4a7e-a9af-ba2e66cc1caf)
![image](https://github.com/user-attachments/assets/d79c674d-1db5-4186-81b2-d3bf9271cab6)

**Comment by ahcorde** [comment]
Thank you for testing!
