### ISSUE TITLE
gz-sim: joint_position_controller.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1628]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/joint_position_controller.sdf)

**Comment by bperseghetti** [comment]
I'm available to test.

**Comment by akky20** [comment]
## Spawing without simulation
![image](https://github.com/user-attachments/assets/6ac4fe48-aaf3-4d79-9e6b-e71b7f27e146)

## With the Topics
![image](https://github.com/user-attachments/assets/68c452eb-4c81-4812-8aa3-8f4513f15315)
![image](https://github.com/user-attachments/assets/be22b84e-bb2b-423c-b605-b81b75ea508e)

**Comment by ahcorde** [comment]
Thank you for testing!
