### ISSUE TITLE
gz-sim: kinetic_energy_monitor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1630]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/kinetic_energy_monitor.sdf)

**Comment by alesof** [comment]
## Configuration
Running on Ubuntu 22.04 using the suggested docker setup. Gazebo version is 9.0.0~pre1.

## Process
Instructions works.
Test simulation running: `gz sim kinetic_energy_monitor.sdf`
Test cli topic output: `gz topic -et "/model/sphere/kinetic_energy"`

Default Output: `data: 132.21308034029974`

Output correctly matches height (i.e. higher start pose corresponds to increase of kinetic energy). 
Threshold set in the sdf works.
