### ISSUE TITLE
gz-sim: levels_no_performers.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1632]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/levels_no_performers.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
Works as expected !

**Comment by arjo129** [comment]
Images/video?

**Comment by avanmalleghem** [comment]
Here it is :)
[Screencast from 03-09-24 09:38:20.webm](https://github.com/user-attachments/assets/fb39cf6d-c7e1-4103-9291-cf8941bcb77c)

**Comment by ahcorde** [comment]
Thank you for testing!
