### ISSUE TITLE
gz-sim: lift_drag.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1633]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/lift_drag.sdf)

**Comment by akky20** [comment]
No Issues, Here is the images for the reference 

![image](https://github.com/user-attachments/assets/90d7327c-6937-481c-8816-2bbe9d6c8ffa)
![image](https://github.com/user-attachments/assets/b7377d03-fc1e-48cc-a0d4-d3cb691f2d26)
![image](https://github.com/user-attachments/assets/bf7e3bd5-1994-4e92-a7be-ba8aa9c42c4c)

**Comment by ahcorde** [comment]
Thank you for testing!
