### ISSUE TITLE
gz-sim: lift_drag_battery.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1634]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/lift_drag_battery.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-31-2024 02:03:45 PM.webm](https://github.com/user-attachments/assets/651c0077-caa8-4b46-a2b7-f3b4b9373b91)

**Comment by ahcorde** [comment]
Thank you for testing!
