### ISSUE TITLE
gz-sim: lift_drag_nested.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1635]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/lift_drag_nested.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy) ##
[Screencast from 08-31-2024 12:32:37 AM.webm](https://github.com/user-attachments/assets/6b2208fc-0d1c-4add-b7e0-44f3d4831860)

**Comment by ahcorde** [comment]
Thank you for testing!
