### ISSUE TITLE
gz-sim: lighter_than_air_blimp.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1636]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/lighter_than_air_blimp.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
![image](https://github.com/user-attachments/assets/b183ee19-3970-4840-9d60-de1fa12e38d7)

Works as expected, not a lot of indications.
