### ISSUE TITLE
gz-sim: lightmap.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1637]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/lightmap.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
Works like a charm
![image](https://github.com/user-attachments/assets/465b47fd-bd82-4f4e-82d3-b6b25e16a307)
