### ISSUE TITLE
gz-sim: log_record_dbl_pendulum.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1640]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/log_record_dbl_pendulum.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
It seems like `gz sim --playback ~/.gz/sim/log/<timestamp>` is not working. Maybe because I run it into your docker setup ? Otherwise, the record seems ok
![image](https://github.com/user-attachments/assets/d38569ec-3762-4b50-9120-946ba8c98198)

For example, I launched `gz sim -v 4 --playback ~/.gz/sim/log/2024-08-31T14\:06\:29.302105487`and it doesn't work and don't show any interesting error logs.

**Comment by arjo129** [comment]
Yes. I can confirm the playback is not working.

**Comment by avanmalleghem** [comment]
@arjo129 is it a docker related issue or even on an ubuntu host ? How can we progress on this one ?

**Comment by arjo129** [comment]
It is an issue on the host as well. Im currently investigating.

**Comment by arjo129** [comment]
After some insane Spelunking of the code base there is a bug in the way the GUI and the server synchronize the world name. The GUI client queries what it thinks is the world name. The server sends a world name that does not match what the world name in the log file is.

Evidence of this issue can be seen in this screenshot:

**Comment by arjo129** [comment]
PR opened: https://github.com/gazebosim/gz-sim/pull/2590

**Comment by avanmalleghem** [comment]
Isn't the issue related to the way gui config is managed ? I see in https://gazebosim.org/api/sim/9/gui_config.html : "For log-playback, the default file is $HOME/.gz/sim/<#>/playback_gui.config".

**Comment by azeey** [comment]
hmm, we should check if this is related to https://github.com/gazebosim/gz-sim/pull/2497

**Comment by arjo129** [comment]
@azeey I dont think this has to do with config files. Ive got a full fiz for this already in gazebosim/gz-sim#2590. Its a regression becaise of refactors to `SimulationRunner`
