### ISSUE TITLE
gz-sim: log_record_keyboard.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1641]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/log_record_keyboard.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
Waiting for https://github.com/gazebosim/gazebo_test_cases/issues/1640

**Comment by avanmalleghem** [comment]
Works as expected : 
![image](https://github.com/user-attachments/assets/02d7cf75-12a4-45a9-a21d-8e0d6b372c2a)
