### ISSUE TITLE
gz-sim: log_record_resources.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1642]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/log_record_resources.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
Waiting for https://github.com/gazebosim/gazebo_test_cases/issues/1640

**Comment by avanmalleghem** [comment]
It works as expected 
![image](https://github.com/user-attachments/assets/8711f8a3-c4cf-414d-877f-eb31e3fcb504)
