### ISSUE TITLE
gz-sim: logical_audio_sensor_plugin.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1644]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/logical_audio_sensor_plugin.sdf)

**Comment by avanmalleghem** [comment]
Interested in !

**Comment by avanmalleghem** [comment]
The tutorial in the SDF file works as expected ! Can be closed !

**Comment by ahcorde** [comment]
Thank you for testing!
