### ISSUE TITLE
gz-sim: logical_camera_sensor.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1645]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/logical_camera_sensor.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Gazebo Logical Camera Sensor Demo

![logical_cam](https://github.com/user-attachments/assets/064096e6-49be-4451-83fa-0549fe298d69)
