### ISSUE TITLE
gz-sim: mimic_fast_slow_pendulums_world.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1648]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/mimic_fast_slow_pendulums_world.sdf)

**Comment by alesof** [comment]
Interested ✋🏼

**Comment by alesof** [comment]
sdf world is correctly working. Screenshot attached for future documentation.

## Running simulation
![pendulum](https://github.com/user-attachments/assets/ce7b7248-c9f8-437e-bf83-29e3b1def7c6)
