### ISSUE TITLE
gz-sim: model_photo_shoot.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1650]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/model_photo_shoot.sdf)

**Comment by alesof** [comment]
Interested ✋🏼

**Comment by alesof** [comment]
## Configuration
Running on Ubuntu 22.04 using the suggested docker setup. Gazebo version is 9.0.0~pre1.

## Process
Step1: The simulation works. Several debug outputs are printed to console, don't know if it is the desired behaviour. 

To test the simulation:
```
gz sim  -s -r -v 4 \-\-iterations 50 model_photo_shoot.sdf
```

Produced output matches the description and attached.

![1](https://github.com/user-attachments/assets/5ad9f926-9c77-4cfc-a3b8-84742d17c7c2)
![2](https://github.com/user-attachments/assets/1b78cfae-9243-4a30-9435-060d67a5c95f)
![3](https://github.com/user-attachments/assets/21c7b3df-72d1-43b8-9404-fe581436632a)
![4](https://github.com/user-attachments/assets/2d523dcb-01eb-4935-92f5-da5d2332b9cd)
![5](https://github.com/user-attachments/assets/36226d47-1a7c-444f-ba81-56b2e5dccbbe)
