### ISSUE TITLE
gz-sim: multicopter_velocity_control.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1652]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/multicopter_velocity_control.sdf)

**Comment by akky20** [comment]
## When we spawn the models
![Screenshot from 2024-08-31 14-47-01](https://github.com/user-attachments/assets/253ad53b-ba32-45b0-8885-5f9b97cac717)

## Start the simulation
![Screenshot from 2024-08-31 14-47-06](https://github.com/user-attachments/assets/975b5849-acfe-4f64-b004-bd15487f2938)

## when we give command to quadcopter to straight up and then hover
![Screenshot from 2024-08-31 14-48-30](https://github.com/user-attachments/assets/79f1a3c2-fd0f-4d2c-b915-cadc425680a8)
![Screenshot from 2024-08-31 14-47-39](https://github.com/user-attachments/assets/17922999-30c5-4705-9c1f-94fe8fa252d7)

## odometry and pose result 
![Screenshot from 2024-08-31 14-49-12](https://github.com/user-attachments/assets/e5a0c3ad-15b0-49b9-8164-5e3d34771d48)
![Screenshot from 2024-08-31 14-49-00](https://github.com/user-attachments/assets/357cb541-596b-4cae-8ed3-92383b42774d)

# Now for hexacopter
![Screenshot from 2024-08-31 14-50-53](https://github.com/user-attachments/assets/1fa8ec8a-06eb-4a88-884b-c5c806ae74b2)
![Screenshot from 2024-08-31 14-50-42](https://github.com/user-attachments/assets/a0e65d27-1349-4460-8215-2770766657e5)

![Screenshot from 2024-08-31 14-50-14](https://github.com/user-attachments/assets/1c66da5e-a475-4549-9b9b-fd269fd85d32)

**Comment by ahcorde** [comment]
Thank you for testing!
