### ISSUE TITLE
gz-sim: nested_model.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1653]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/nested_model.sdf)

**Comment by jennuine** [comment]
Testing on ubuntu noble using binaries. Looks good, tested turning on collisions for only nested model:
<img width="1201" alt="Screenshot 2024-08-30 at 11 30 46 AM" src="https://github.com/user-attachments/assets/a562437e-6a65-462c-9273-19b23610beba">
