### ISSUE TITLE
gz-sim: nested_model_joint_positions.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1654]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/nested_model_joint_positions.sdf)

**Comment by j-rivero** [comment]
Works well on Ubuntu Noble via docker on i915. I notice a drop in the RTF with respect to Harmonic of about 8%.
