### ISSUE TITLE
gz-sim: optical_tactile_sensor_plugin.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1655]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/optical_tactile_sensor_plugin.sdf)

**Comment by akky20** [comment]
![Screenshot from 2024-08-31 03-19-49](https://github.com/user-attachments/assets/1fa5f211-a6cf-46c4-8a2e-33af5eb65dc2)

Spawing perfectly, but yes whenever I run simulation the gui stops with these console logs 
![image](https://github.com/user-attachments/assets/5a797cb6-f862-48e4-908f-6895f2a08281)

**Comment by iche033** [comment]
created https://github.com/gazebosim/gz-sim/pull/2561 to fix the crash.
