### ISSUE TITLE
gz-sim: particle_emitter.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1656]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/particle_emitter.sdf)

**Comment by iche033** [comment]
created https://github.com/gazebosim/gz-sim/pull/2560 to get rid of the error msg

**Comment by ahcorde** [comment]
PR is merged, Thank you for testing!
