### ISSUE TITLE
gz-sim: perfect_comms.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1658]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/perfect_comms.sdf)

**Comment by akky20** [comment]
I'm interest

**Comment by akky20** [comment]
![Screenshot from 2024-08-31 03-12-31](https://github.com/user-attachments/assets/647cd6c1-3414-48b0-93cb-a0fb882e047f)

Works fine

**Comment by azeey** [comment]
The instructions in the .SDF file say
  Gazebo perfect-comms plugin demo.

 
>  Compile the comms publisher:
>     cd gz-sim/examples/standalone/comms
>     mkdir build
>     cd build
>     cmake ..
>     make
> 
>   Try launching a comms subscriber:
>     gz topic -e -t addr2/rx
> 
>   Try launching a comms publisher:
>     ./publisher addr2

Can you confirm if you followed those steps?

**Comment by akky20** [comment]
![image](https://github.com/user-attachments/assets/0e85396f-fdb1-4627-a0d9-690ecd4161bd)

yes here it is , but for subscribing I use `gz topic -e -t /broker/msgs` as with `gz topic -e -t addr2/rx
` its not subscribing anything
