### ISSUE TITLE
gz-sim: performer_detector.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1659]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/performer_detector.sdf)

**Comment by jennuine** [comment]
Tested with ubuntu nobile using binaries. Looks good, both PerformerDetector's were detected when the vehicle entered.
<img width="1404" alt="Screenshot 2024-08-30 at 11 27 52 AM" src="https://github.com/user-attachments/assets/1096c6a9-019a-4029-a48d-b384dc81b26f">
