### ISSUE TITLE
gz-sim: physics_options.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1660]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/physics_options.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Physics Option Setup Demo

![sim_init](https://github.com/user-attachments/assets/38977fd2-ae9e-427e-a7b2-b81493934237)

### Physics Option Play Demo

![sim_play](https://github.com/user-attachments/assets/09b4c510-6f98-41cc-8a00-8da313727ea2)
