### ISSUE TITLE
gz-sim: plane_propeller_demo.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1661]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/plane_propeller_demo.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
[Screencast from 08-30-2024 08:19:58 PM.webm](https://github.com/user-attachments/assets/d1d5e58c-bc49-438b-b3de-1723e055b574)
