### ISSUE TITLE
gz-sim: polylines.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1663]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/polylines.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Polylines Simulation 

![polyline_before](https://github.com/user-attachments/assets/5004c0ef-f414-443a-8270-fe9e3a6451fa)

### After Playing Simulation

![polyline_after](https://github.com/user-attachments/assets/302aadd3-6322-4bdd-a13a-3237ef36ea93)
