### ISSUE TITLE
gz-sim: pose_publisher.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1664]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/pose_publisher.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Pose Publisher Demo

![pose_pub](https://github.com/user-attachments/assets/57b22700-4177-4325-beef-a4680cc7f22d)
