### ISSUE TITLE
gz-sim: projector.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1665]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/projector.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Projector Model Demo

![projector_demo](https://github.com/user-attachments/assets/978c12c6-fdcb-4ccd-81e7-d14daaf1d53a)
