### ISSUE TITLE
gz-sim: python_system_loader.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1666]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/python_system_loader.sdf)

**Comment by jennuine** [comment]
Testing using Ubuntu Nobile with binaries. Looks good.

<img width="1186" alt="Screenshot 2024-08-30 at 11 23 34 AM" src="https://github.com/user-attachments/assets/1c9345d6-2da5-4102-a6e0-421f407edb38">
