### ISSUE TITLE
gz-sim: quadcopter.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1667]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/quadcopter.sdf)

**Comment by david-dorf** [comment]
[Screencast from 2024-08-31 14-53-04.webm](https://github.com/user-attachments/assets/2361b09e-a2d0-4205-9d9e-bdb0689434da)
LGTM

**Comment by ahcorde** [comment]
Thank you for testing!
