### ISSUE TITLE
gz-sim: rf_comms.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1669]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/rf_comms.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
![Screenshot from 2024-08-30 20-15-55](https://github.com/user-attachments/assets/1a805d9a-a194-42c4-a09e-149d430bb2c9)
