### ISSUE TITLE
gz-sim: rolling_shapes.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1670]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/rolling_shapes.sdf)

**Comment by bperseghetti** [comment]
I'm available to test.

**Comment by david-dorf** [comment]
They be rolling, even after the visual plane ends... Maybe a problem with the Plane geometry? The SDF of the world looked fine
[Screencast from 2024-08-31 14-46-59.webm](https://github.com/user-attachments/assets/81de046b-7050-4bba-8cef-a346643cc8ba)

**Comment by ahcorde** [comment]
The plane is not infinite. Thank you for testing!
