### ISSUE TITLE
gz-sim: segmentation_camera.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1671]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/segmentation_camera.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Segmentation Camera Demo - Semantic & Instance Segmentation

![seg_cam_demo](https://github.com/user-attachments/assets/6ef3aef2-25b4-4373-8ad4-6bff7a0b8510)
