### ISSUE TITLE
gz-sim: sensors.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1672]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/sensors.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Gazebo sensor demo for sensors that do not require rendering

## Altimeter: 

```gz topic -e -t /altimeter```

![altimeter_reading](https://github.com/user-attachments/assets/fd814cd0-d5ba-49db-a8cb-0e119712087b)

##  Imu: 

```gz topic -e -t /imu```

![imu_reading](https://github.com/user-attachments/assets/79b25ac4-d41e-4e6d-bcde-741bec8c8ae8)

##  Magnetometer: 

```gz topic -e -t /magnetometer```

![magnetometer_reading](https://github.com/user-attachments/assets/9aec97be-0063-4755-a429-66a87fe1a0a5)

##  Air pressure: 

```gz topic -e -t /air_pressure```

![air_pressure_reading](https://github.com/user-attachments/assets/499455d4-3660-4623-a710-ab4233290765)

**Comment by ahcorde** [comment]
Thank you for testing!
