### ISSUE TITLE
gz-sim: sensors_demo.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1673]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/sensors_demo.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Sensor Demo 

![sensor demo](https://github.com/user-attachments/assets/21cad876-3613-4e0d-a8e0-40c085abfdbb)
