### ISSUE TITLE
gz-sim: shader_param.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1674]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/shader_param.sdf)

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Shader Param
This world contains a sphere model whose visual appearance is altered by the
ShaderParam visual plugin over time.

#### At time t0

![initial_shader_t0](https://github.com/user-attachments/assets/a49128fe-45ec-4571-b299-e65d6b23911a)

#### At time t1

![Screenshot from 2024-08-29 23-41-46](https://github.com/user-attachments/assets/460d2671-1ad5-4155-8185-445eff74b7ae)

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Shader Param
This world contains a sphere model whose visual appearance is altered by the
ShaderParam visual plugin over time.

#### At time t0

![initial_shader_t0](https://github.com/user-attachments/assets/a49128fe-45ec-4571-b299-e65d6b23911a)

#### At time t1

![Screenshot from 2024-08-29 23-41-46](https://github.com/user-attachments/assets/460d2671-1ad5-4155-8185-445eff74b7ae)
