### ISSUE TITLE
gz-sim: shapes.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1675]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/shapes.sdf)

**Comment by bperseghetti** [comment]
I'm available to test.

**Comment by akky20** [comment]
Tested succesfully
[Screencast from 01-09-24 01:21:08 AM IST.webm](https://github.com/user-attachments/assets/1ae1a141-de88-433b-aca3-166d1537ab96)

**Comment by ahcorde** [comment]
Thank you for testing!
