### ISSUE TITLE
gz-sim: skid_steer_mecanum.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1677]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/skid_steer_mecanum.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Testing Gazebo demo of skid steer with Mecanum wheels using differential drive plugin

#### Running Simulation

![Screenshot from 2024-08-29 23-47-30](https://github.com/user-attachments/assets/f3c99b43-b8d0-4cc4-9a8b-51d9dba55a79)

#### Reading Odometry

![Screenshot from 2024-08-29 23-48-19](https://github.com/user-attachments/assets/44509308-0064-4a94-9b51-cd8a16c3b949)

**Comment by azeey** [comment]
Thanks!
