### ISSUE TITLE
gz-sim: sky.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1678]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/sky.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Demo of world with sky

![sky_enabled](https://github.com/user-attachments/assets/54d9ae4d-c9b2-40a2-8ff6-6137adb718ac)
