### ISSUE TITLE
gz-sim: spacecraft.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1679]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/spacecraft.sdf)

**Comment by Mechazo11** [comment]
interested

**Comment by bperseghetti** [comment]
I can test as well.

**Comment by david-dorf** [comment]
[Screencast from 2024-08-31 14-31-33.webm](https://github.com/user-attachments/assets/beb67ba5-dc1e-460c-92e5-a80057ffa780)
LGTM, odom and thrusters worked as expected

**Comment by Mechazo11** [comment]
* **Test enviornment**
    ```text
    CPU: Ryzen 5 5600x, Ram: 32GB @ 3200 Mhz, GPU: RTX 3080
    Clean copy of Ubuntu 24.04 Humble
    ROS 2 Jazzy Jalisco Full Desktop 
    ```
* **Summary**
    * ```spacecraft.sdf``` world opens successfully with no issue. Space craft changes attitude when ```gz topic -p 'normalized:[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]' -t /dart/command/duty_cycle --msgtype gz.msgs.Actuators``` is passed and odometry is updated accordingly.

![spacecraft](https://github.com/user-attachments/assets/6bfe9a72-5e07-45c1-ac60-bef718a0df67)

* **Issues**
    * N/A
    
* **Fixes**
    * N/A

* **Comments/Suggestions**
    * N/A

**Comment by ahcorde** [comment]
Thank you for testing!
