### ISSUE TITLE
gz-sim: spaces.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1680]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/spaces.sdf)

**Comment by Mechazo11** [comment]
Interested

**Comment by david-dorf** [comment]
![image](https://github.com/user-attachments/assets/eae84d0d-1579-4c80-973a-6e839f03f046)
LGTM, everything is there and no errors/warnings

**Comment by Mechazo11** [comment]
* **Test enviornment**
    ```text
    CPU: Ryzen 5 5600x, Ram: 32GB @ 3200 Mhz, GPU: RTX 3080
    Clean copy of Ubuntu 24.04 Humble
    ROS 2 Jazzy Jalisco Full Desktop 
    ```
* **Summary**
    * ```spaces.sdf``` world opens successfully with no issue.

* **Issues**
    * N/A
    
* **Fixes**
    * N/A

* **Comments/Suggestions**
    * N/A

**Comment by ahcorde** [comment]
Thank you for testing!
