### ISSUE TITLE
gz-sim: spherical_coordinates.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1681]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/spherical_coordinates.sdf)

**Comment by jennuine** [comment]
Testing successful using binaries, at startup world is using set spherical coordinates:
<img width="1796" alt="Screenshot 2024-08-30 at 11 08 53 AM" src="https://github.com/user-attachments/assets/bb448add-d1dd-4559-a2c3-834ed0dfeab9">

Update spherical coordinates:
<img width="1799" alt="Screenshot 2024-08-30 at 11 10 41 AM" src="https://github.com/user-attachments/assets/67229a8b-d9ed-4034-ba51-9c8cf341d592">

Spawn a model in spherical coordinates:
<img width="1795" alt="Screenshot 2024-08-30 at 11 16 01 AM" src="https://github.com/user-attachments/assets/9e01a13f-a621-4e33-b95e-9ef1c294a2ff">

And move model in spherical coordinates.
