### ISSUE TITLE
gz-sim: thermal_camera.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1682]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/thermal_camera.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Thermal Camera Sensor Demo

![termal_cam](https://github.com/user-attachments/assets/47539402-cd8b-46d2-b526-b77976971857)
