### ISSUE TITLE
gz-sim: touch_plugin.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1683]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/touch_plugin.sdf)

**Comment by Combuster54** [comment]
Interested

**Comment by Combuster54** [comment]
## Ubuntu 24.04 Noble

Running touch_plugin.sdf
```bash
gz sim touch_plugin.sdf
```
![image](https://github.com/user-attachments/assets/17ed4fca-4e66-4391-af7a-3e7c0a054b7f)

touch plugin is able by default 

![image](https://github.com/user-attachments/assets/bdea6f41-61b1-4da7-8b8f-d963f87636bd)

after certain time in contact, plugin sends true

## Conclusion
touch plugin works as expected

**Comment by ahcorde** [comment]
Thank you for testing!
