### ISSUE TITLE
gz-sim: track_drive.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1684]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/track_drive.sdf)

**Comment by khshmt** [comment]
Interested

**Comment by khshmt** [comment]
## Ubuntu 22.04 (jammy)
[Screencast from 08-31-2024 12:32:37 AM.webm](https://github.com/user-attachments/assets/65ea2661-ce71-40ed-b289-a6f8d2a22068)

**Comment by azeey** [comment]
I noticed you used Jammy. Can you confirm you used Gazebo Ionic? You can find from the about dialog in the [hamberger menu](https://en.wikipedia.org/wiki/Hamburger_button)?

**Comment by khshmt** [comment]
![Screenshot from 2024-08-31 01-52-12](https://github.com/user-attachments/assets/543498cf-91b7-4c88-96b9-521ed60240f7)

**Comment by ahcorde** [comment]
Thank you for testing!
