### ISSUE TITLE
gz-sim: triggered_publisher.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1688]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/triggered_publisher.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Gazebo Trigger Publisher Demo

![ini_setup](https://github.com/user-attachments/assets/6c2ad942-e459-478e-b351-5cbfab179597)

### First Box Drop After Vehicle Crosses Line On Ground

![after_first_box](https://github.com/user-attachments/assets/9da99ecb-4bb5-4d5a-bd22-d197c54f4a93)

### After Five Simulation Second

![after_second_box](https://github.com/user-attachments/assets/25cbf166-c4c5-4362-9e8c-6be51f43e5a8)
