### ISSUE TITLE
gz-sim: trisphere_cycle_wheel_slip.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1689]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/trisphere_cycle_wheel_slip.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Gazebo Trisphere Wheel Slip Plugin demo

![initial_setup](https://github.com/user-attachments/assets/5a7593c6-12f4-469d-b55f-fba6d0c186f9)

### Simulation Play

![sim_play](https://github.com/user-attachments/assets/5d5865ce-3c22-436a-960d-19f46b678194)
