### ISSUE TITLE
gz-sim: video_record_dbl_pendulum.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1692]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/video_record_dbl_pendulum.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Simulation Play

![robot_play](https://github.com/user-attachments/assets/41cae829-161b-41b5-9fd8-1855db1173d4)

### MP4 Recording Test

![mp4_test](https://github.com/user-attachments/assets/6ba741dd-8baa-4f5f-8c09-4a8e562aab8d)

### OGV Recording Test

![ogv_test](https://github.com/user-attachments/assets/858dc0f0-de2f-4819-b4cc-e90b414293ec)
