### ISSUE TITLE
gz-sim: wide_angle_camera.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1696]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/wide_angle_camera.sdf)

**Comment by Narashima1808** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/151552a6-da2e-4c10-bb4b-d4455e9d563c" />

Using Docker,Ubuntu Noble

[status:passed]
