### ISSUE TITLE
gz-sim: wind.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1697]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/wind.sdf)

**Comment by trushant05** [comment]
I am interested in testing this out.

**Comment by trushant05** [comment]
## Ubuntu 24.04 (Noble)

### Initial Simulation Play

![wind_direc_initial](https://github.com/user-attachments/assets/9ba51adc-fcc5-4143-8a69-644dc4390804)

### Setting New Wind Speed

![setting_new_wind_vel](https://github.com/user-attachments/assets/c36e79c1-c3d0-4991-951d-14dc874ebf3f)

### After Wind Speed Update

![after_wind_vel_change](https://github.com/user-attachments/assets/df21b845-7e7d-4f62-8154-76cfb00c16fa)
