### ISSUE TITLE
docs: install_windows_src

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#17]
## Setup
- Os: Windows
- BuildType: Source

## Links
- [Live](https://gazebosim.org/docs/harmonic/install_windows_src)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/install_windows_src.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by peci1** [comment]
I'm trying this on Windows 10.

**Comment by peci1** [comment]
Hit by https://github.com/gazebosim/sdformat/pull/1319 . But a fix should be coming. Manually fixing it makes sdformat compilable.

**Comment by peci1** [comment]
Requires a new conda release of libzip: https://github.com/conda-forge/libzip-feedstock/pull/37 .

Workaround:

    conda install libzip=1.9.2 --channel conda-forge

**Comment by Voldivh** [comment]
Thanks for addressing this @peci1, let's wait for related PRs to be merged before we close this issue.

**Comment by peci1** [comment]
All code-level changes were merged. I've tested now with the newest branches and was able to compile and run Gazebo according the the (not yet merged) updated tutorial.

**Comment by Voldivh** [comment]
> All code-level changes were merged. I've tested now with the newest branches and was able to compile and run Gazebo according the the (not yet merged) updated tutorial.

That's great to hear @peci1, let's wait until that last PR is merged before closing this issue.

**Comment by peci1** [comment]
The docs PR is merged, too!

**Comment by Voldivh** [comment]
Thanks a lot @peci1! Finally closing this issue as completed :D
