### ISSUE TITLE
docs: Manipulating_models

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#18]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/manipulating_models)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/Manipulating_models.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by athackst** [comment]
Hey! It doesn't look like the link in the `links` section works here.

It should be https://gazebosim.org/docs/harmonic/manipulating_models for "live"

I suspect this has to do with changing case between the source (Manipulating_models.md) and the published page (manipulating_models)

**Comment by Voldivh** [comment]
Thanks @athackst the link should be working now. Did you manage to try out the tutorial?

**Comment by athackst** [comment]
Yep!

The instructions appear to work and the images match the result

**Comment by Voldivh** [comment]
Thanks @athackst I'll be closing this as closed
