### ISSUE TITLE
gz-sensors: Segmentation Camera in Gazebo

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#185]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sensors/8/segmentationcamera_igngazebo.html)
- [Source](https://github.com/gazebosim/gz-sensors/tree/gz-sensors8/tutorials/segmentation_camera.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by iche033** [comment]
updated [hatchback blue](https://app.gazebosim.org/OpenRobotics/fuel/models/Hatchback%20blue) model on fuel - replaced references to ignitionrobotics.org with gazebosim.org in mtl file

**Comment by Voldivh** [comment]
Should we consider this issue addressed or not yet @iche033 ?

**Comment by iche033** [comment]
Not yet. I still need to test some other parts of this tutorial.

**Comment by iche033** [comment]
the python script in the tutorial throws the error below:

```
TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

looks like it's an opencv issue: https://github.com/opencv/opencv/issues/23822. Fix is not yet released yet. Easiest thing we could do is wait for 4.9.0 release
