### ISSUE TITLE
gz-sim: 3k_shapes.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#188]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/3k_shapes.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by mjcarroll** [comment]
It loads and runs. I'm getting 0.15% RTF.

**Comment by mjcarroll** [comment]
![image](https://github.com/gazebosim/gazebo_test_cases/assets/279701/5b704cd7-f44c-4448-8d60-61820298d31f)
