### ISSUE TITLE
gz-sim: actor.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#196]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/actor.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
