### ISSUE TITLE
gz-sim: Apply Force and Torque

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#199]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/apply_force_torque.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/apply_force_torque.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by AndrejOrsula** [comment]
Following the tutorial, the Force Torque plugin **works great and everything is well explained**.

However, I experienced an **issue** with the viewport when this plugin is **combined with translation/rotation modes** (user commands) - see the video below. I am not sure what is causing the issue and it might be unrelated.

https://github.com/gazebosim/gazebo_test_cases/assets/22929099/009e48e7-2606-4b20-8b6d-cb1129031802

> Disclaimer: Tested inside Docker (base image: `ubuntu:jammy` | build type: `source`)

**Comment by azeey** [comment]
Ah, yeah, I think that's the behavior of the Transform tool where it basically keeps the pose of the visual from being updated once it's activated on the object. Perhaps we should consider it a bug. In the video below, the tool is activated on the cube, which keeps it from falling. In reality, physics will have actually updated the pose of the cube and as soon as the transform tool is deactivated, the visual for the cube snaps to its updated position.

[Screen recording 2023-09-13 17.34.05.webm](https://github.com/gazebosim/gazebo_test_cases/assets/206116/b56231fc-394f-4297-b3ee-0973c9710501)

**Comment by Voldivh** [comment]
I believe we can close this one @azeey I believe the behavior we observed is the expected.
