### ISSUE TITLE
gz-sim: auv_controls.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#202]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/auv_controls.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Hello! 

Yeah, works perfectly! Here is the gif:
![auv_control](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/b8992c0b-3ccb-4c3d-8e2b-d36bdd8d34cc)

If any additional tests are needed, let me know.

**Comment by Voldivh** [comment]
Thanks @matosinho
