### ISSUE TITLE
gz-sim: Blender SDF Exporter

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#207]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/blender_sdf_exporter.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/blender_sdf_exporter.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Hello!

I was partially successfull with the tutorial. I was able to use the script to generate the .sdf file, but they didn't export the material of the parts with colors. In the tutorial it commented that this might not be possible as well. I guess only with textures and UV mapping it would work, but I couldn't make it happen. If someone can share a tutorial or tips of how exporting the models from Blender with material or how to config the UV mapping to also be converted it would be nice.

Here is a picture of the world in blender:
![Screenshot from 2023-09-10 17-08-13](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/f9c17218-4e91-4601-9f83-72176be93a49)

Here it is the export in gazebo:
![Screenshot from 2023-09-10 17-08-46](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/43f0dd45-d590-454a-8b75-2f89d3213d2b)

Here are the warnings on the terminal:
```
Warning [Utils.cc:130] [/sdf/model[@name="test"]/link[@name="testlink"]/collision[@name="collision"]/contact:/home/matosinho/dev/gazebo_harmonic_tutorial_party/example_tutorials/model.sdf:L63]: XML Element[contact], child of element[collision], not defined in SDF. Copying[contact] as children of [collision].
Warning [Utils.cc:130] [/sdf/model[@name="test"]/link[@name="testlink"]/collision[@name="collision"]/collide_bitmask:/home/matosinho/dev/gazebo_harmonic_tutorial_party/example_tutorials/model.sdf:L64]: XML Element[collide_bitmask], child of element[collision], not defined in SDF. Copying[collide_bitmask] as children of [collision].
Warning [Utils.cc:130] [/sdf/static:/home/matosinho/dev/gazebo_harmonic_tutorial_party/example_tutorials/model.sdf:L68]: XML Element[static], child of element[sdf], not defined in SDF. Copying[static] as children of [sdf].
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
Warning [Utils.cc:130] [/sdf/model[@name="test"]/link[@name="testlink"]/collision[@name="collision"]/contact:<data-string>:L61]: XML Element[contact], child of element[collision], not defined in SDF. Copying[contact] as children of [collision].
Warning [Utils.cc:130] [/sdf/model[@name="test"]/link[@name="testlink"]/collision[@name="collision"]/collide_bitmask:<data-string>:L62]: XML Element[collide_bitmask], child of element[collision], not defined in SDF. Copying[collide_bitmask] as children of [collision].
```

If any additional tests need to be made, let me know.

**Comment by azeey** [comment]
https://github.com/gazebosim/gz-sim/pull/2156 should fix the warnings. I'll go ahead and close this since the instructions work.
