### ISSUE TITLE
gz-sim: boundingbox_camera.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#209]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/boundingbox_camera.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Working .
![Screenshot from 2023-09-10 23-37-25](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/ffe4cfca-468e-4da7-adaa-228cc342bcc9)

With Few warnings , on terminal . 
```
Warning [Utils.cc:130] [/sdf/plugin[@name="gz::sim::systems::Label"]:<data-string>:L1]: XML Element[plugin], child of element[sdf], not defined in SDF. Copying[plugin] as children of [sdf]
```

**Comment by Voldivh** [comment]
Thanks @jchaudhary21 I'll file an issue report.
