### ISSUE TITLE
gz-sim: breadcrumbs.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#210]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/breadcrumbs.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
If I include a camera in the world, the object is removed from the GUI, but it still visible in the camera. 

Similar issue described here https://github.com/gazebosim/gz-sensors/issues/339
