### ISSUE TITLE
gz-sim: buoyancy_engine.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#211]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/buoyancy_engine.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Hello!

All works well. I tested to change the buoayncy engine values and it happens what it was described on the tutorial. First the boxes went up and with the next command went down. Here is a 1 minute long gif showing the results:

![buoyancy_engine](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/3165b53b-34a1-4a85-b980-7f9f4eb38031)

If any additional test or feedback is needed, let me know.
