### ISSUE TITLE
gz-sim: buoyancy.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#212]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/buoyancy.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Hello! 

For the default `buoyancy.sdf` file the example is working fine. Here is a gif:
![buoyancy](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/944d0349-c0ce-4213-af63-7de22dcb9eed)

Although, changing the buoayancy a little the example crashed. For a density of 800, here is what I get after some time:
![crash_buoancy](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/9ad587bd-52fc-42f3-a4ca-694c283b2fce)

It is a very similar problem from the one I'm having here: https://github.com/gazebosim/gazebo_test_cases/issues/299#issuecomment-1712092668

Maybe is on the damping plugin or control surfaces plugins...

If any additional test is needed, let me know.

**Comment by azeey** [comment]
@mabelzhang or @arjo129 do you know why this might be happening?

**Comment by iche033** [comment]
> Although, changing the buoayancy a little the example crashed.
Looking at the error msg you have from https://github.com/gazebosim/gazebo_test_cases/issues/299#issuecomment-1712092668: 

```
 `ODE INTERNAL ERROR 1: assertion "aabbBound >= dMinIntExact && aabbBound < dMaxIntExact" failed in collide() [collision_space.cpp:460]`
```

I think the models probably continued to fall / float so their positions end up in really large values, resulting in `nan` or `inf` during collision checking.

**Comment by arjo129** [comment]
There is no damping in this example. As @iche033 said if you keep running it the model will continue to fall/float resulting in `NaN`s. Not sure what we should do about it.

**Comment by azeey** [comment]
Okay, I'll go ahead and close this since the example, as it's written, works fine. Fixing the damping issue is out of scope for this issue. Feel free to create an issue on gz-sim if necessary.
