### ISSUE TITLE
gz-sim: camera_lens_flare.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#213]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/camera_lens_flare.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Worked on this test case 
Run the given SDF file and here's the output
 At **_Camera topic_** 
![camera_flare_ss](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/09377d25-8f82-4173-975f-fc7334eecbe9)
 At **_wide angle camera topic_** 
![wide_angle_camera_ss](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/014d3b29-b4dd-4de7-93a3-d5fb05832583)

**Comment by Voldivh** [comment]
Thanks @jchaudhary21 !
