### ISSUE TITLE
gz-sim: camera_sensor.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#214]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/camera_sensor.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Here's the video , working as expected

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/25542395-aa91-4e32-a938-4a70f4654cba

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
