### ISSUE TITLE
gz-sim: Collada World Exporter

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#218]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/collada_world_exporter.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/collada_world_exporter.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jmackay2** [comment]
Successfully tested on multiple worlds.

- [x] Instructions work
- [x] Images (if there are any) match the result

**Comment by Voldivh** [comment]
Thanks @jmackay2
