### ISSUE TITLE
gz-sim: Collada World Exporter

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#219]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/collada_world_exporter.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/collada_world_exporter.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by AndrejOrsula** [comment]
Everything works good!
Tested with `shapes.sdf` and `fuel.sdf` (shown below in Blender).

![image](https://github.com/gazebosim/gazebo_test_cases/assets/22929099/4170d79f-60fc-4655-b4ef-9e98c873ca10)

For geometry types that the plugin does not support (capture and ellipsoid), a warning below is printed **as expected**.
```log
[Wrn] [ColladaWorldExporter.cc:249] Unsupported geometry type
```

> Disclaimer: Tested inside Docker (base image: `ubuntu:jammy` | build type: `source`)
