### ISSUE TITLE
docs: Model_insertion_fuel

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#22]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/fuel_insert)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/Model_insertion_fuel.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The link to the live page is not working

**Comment by JACOBIN-SCTCS** [comment]
The resource spawner plugin window is not loading upon selecting it from the options menu. Can somebody check. I have started with an empty world

**Comment by JACOBIN-SCTCS** [comment]
The issue seems to be there even on other plugins. Can somebody else verify too

**Comment by mjcarroll** [comment]
The corrected tutorial link should be: https://gazebosim.org/docs/harmonic/fuel_insert

**Comment by mjcarroll** [comment]
> The resource spawner plugin window is not loading upon selecting it from the options menu. Can somebody check. I have started with an empty world


Can you scroll down in the plugins and verify that it doesn't appear at the bottom of the column?  In my case, it was just slightly offscreen when my window was too small.  Alternatively, try closing the "entity tree" panel.

**Comment by azeey** [comment]
This is an interesting UI issue. It would be great if when a plugin is added, the window that contains the plugin cards scrolls to the newly added plugin. I can create an issue in gz-sim.

**Comment by Voldivh** [comment]
Closing this since Issue have been created.
