### ISSUE TITLE
gz-sim: collada_world_exporter.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#220]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/collada_world_exporter.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Hello!

Very nice the plugin. Here is an screenshot of the .dae file generated on blender:
![Screenshot from 2023-09-10 16-37-35](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/5a35c68e-0cc9-45c5-a6e9-553be345d304)

If any additional tests are need, let me know.

**Comment by Voldivh** [comment]
Thanks @matosinho
