### ISSUE TITLE
gz-sim: conveyor.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#224]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/conveyor.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
This example requires to install libdart13 or compile from source dart. This is not working out of the box. 

Related with this issue: https://github.com/gazebosim/gz-sim/issues/1662

Can we update dart ? @scpeters @azeey

**Comment by scpeters** [comment]
> This example requires to install libdart13 or compile from source dart.

you're right; this example requires https://github.com/dartsim/dart/pull/1626, which was released in [dartsim 6.13](https://github.com/dartsim/dart/blob/0c44ca081bc980cf332a8674f11d8c69ad889928/CHANGELOG.md#L55-L94)

that version is [available in homebrew-core for macOS](https://github.com/Homebrew/homebrew-core/blob/master/Formula/d/dartsim.rb#L4), but [not yet on Ubuntu (even 23.10)](https://packages.ubuntu.com/mantic/libdart-all-dev)

I'll check with @j-rivero about how to get 6.13 into debian and Ubuntu at least for 24.04

in the meantime, I guess we can recommend to install the 22.04 dartsim debs [from the PPA](https://launchpad.net/~dartsim/+archive/ubuntu/ppa)?

* https://launchpad.net/~dartsim/+archive/ubuntu/ppa

**Comment by scpeters** [comment]
related discussion about PPA debs: https://github.com/gazebosim/gz-physics/issues/49#issuecomment-1598403951 and https://github.com/gazebosim/gz-sim/issues/1662#issuecomment-1490170827

**Comment by azeey** [comment]
Closing since this being tracked in https://github.com/gazebosim/gz-sim/issues/1662
