### ISSUE TITLE
gz-sim: dem_moon.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#233]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/dem_moon.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working in binary installation of Gazebo Harmonic.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/cde709c0-da7e-4996-9af8-5521b2a9bdd7

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS
