### ISSUE TITLE
gz-sim: detachable_joint.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#238]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/detachable_joint.sdf)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The state of the breadcrumb isn't getting monitored properly for this simulation. Only after I did a reset did the state of a breadcrumb appeared. Was this the expected behaviour (Attaching video). Can somebody also verify too.


https://github.com/gazebosim/gazebo_test_cases/assets/29516177/2a5570c0-84c9-4c47-8a6b-5653e577544e

**Comment by Voldivh** [comment]
I got the exact same behavior. Could you take a look at it @ahcorde ?

**Comment by iche033** [comment]
I think msgs are published to the state topic only if there is a change in state (attached -> detached or vice versa) as opposed to periodic updates.

Regarding reset causing a msg being published on reset, that probably revealed an issue. It seems like an extra detachable joint is created whenever reset is invoked. It could be a bug.

**Comment by Voldivh** [comment]
> I think msgs are published to the state topic only if there is a change in state (attached -> detached or vice versa) as opposed to periodic updates.

Yep, just tried it out and works as you explained. Thanks.

>Regarding reset causing a msg to be published on reset, that probably revealed an issue. It seems like an extra detachable joint is created whenever reset is invoked. It could be a bug.

After playing a little bit around with it, the behavior does seems weird. I'm not sure if I understood what you mean by "an extra detachable joint is created...". The msg I received is related to the joints that were part of the simulation before:
[Video](https://github.com/gazebosim/gazebo_test_cases/assets/51831786/52ff546e-4cd4-4878-8778-9e3281226cda)

**Comment by iche033** [comment]
I was looking at the terminal that's running `gz sim`. Everytime I press reset, I see the msg:

```
[Dbg] [Physics.cc:1864] Creating detachable joint [53]
```

The entity number (`[53]` in the above example) keeps increasing so I assumed that new joint entities are created.

**Comment by Voldivh** [comment]
Oh, I'm getting something different when I click reset:
```bash
Msg [NameManager::issueNewName] (Skeleton::Joint | vehicle_blue) The name [fixed] is a duplicate, so it has been renamed to [fixed(1)]
Msg [NameManager::issueNewName] (Skeleton::Joint | vehicle_blue) The name [fixed] is a duplicate, so it has been renamed to [fixed(2)]
```

**Comment by ahcorde** [comment]
can you try this patch ?

https://github.com/gazebosim/gz-sim/pull/2131

This should reattach the models again

**Comment by azeey** [comment]
Closing since PR has been opened
