### ISSUE TITLE
docs: moving_robot

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#24]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/moving_robot)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/moving_robot.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by suresh-venkate** [comment]
Confirming that I was able to get all the plugins working as per the tutorial and also able to move the robot using the arrow keys.

Setup
--------------------
Os: Ubuntu Jammy
Build Type: Binary

Link Used:
-----------------
[https://gazebosim.org/docs/harmonic/moving_robot](url)

**Comment by Voldivh** [comment]
Thanks @suresh-venkate, closing this issue as completed.
