### ISSUE TITLE
gz-sim: elevator.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#243]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/elevator.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
**Working , as expected** 
![Screenshot from 2023-09-09 22-17-42](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/d3e22018-bdb2-4ef1-a274-7d3ad17aadb2)

- **_Minor Bug_** 
Whenever elevator is at the ground floor it doesn't print anything 
![Screenshot from 2023-09-09 22-10-12](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/60c94e11-8903-423e-a923-bcb6cb12f39f)

**Comment by Voldivh** [comment]
Thanks @jchaudhary21 I'll take note of the bug.
