### ISSUE TITLE
gz-sim: empty.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#245]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/empty.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Output Images 
**1. Model Insert**
![Screenshot from 2023-09-07 19-44-49](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/de76d6e0-9fd3-43e1-b18a-fb571ac6e772)
**2. Model Delete**
![Screenshot from 2023-09-07 19-45-09](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/ddac4870-4113-40b8-bc12-664205dcd06a)
 **3. Light Spawn**
![Screenshot from 2023-09-07 19-45-28](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/1ae1cffb-b527-4dae-b982-5a972834419f)
**4. Delete Spawn Light** 
![Screenshot from 2023-09-07 19-45-45](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/15775c7a-e9b9-4a18-b850-4112b724fa0e)
**5. Allow Renaming** 
![Screenshot from 2023-09-07 19-47-51](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/b296fb9e-f661-493e-ae81-2ed7b8618c50)

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
