### ISSUE TITLE
gz-sim: fuel.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#256]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/fuel.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working in binary installation of Gazebo Harmonic.


https://github.com/gazebosim/gazebo_test_cases/assets/29516177/e636bbd6-5c86-46b2-b546-1df8370e6edf

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS
