### ISSUE TITLE
docs: ros2_integration

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#26]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/ros2_integration)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/ros2_integration.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by suresh-venkate** [comment]
Hi,

I am trying to get ROS2 setup with Gazebo Harmonic. The tutorial page for ROS/Gazebo installation for Gazebo Harmonic ([Link](https://gazebosim.org/docs/harmonic/ros_installation)) doesn't seem to have been updated for Gazebo Harmonic yet. Is there an updated version of this tutorial that explains the compatible ROS version for Harmonic. 

Will there be a humble or iron package that will setup all ros_gz_* packages correctly with Gazebo Harmonic?

Thanks
Suresh

**Comment by Voldivh** [comment]
Hi @suresh-venkate, could you check the links now? The live one and the first one you posted should work. 

On another note, this repo was used only for the tutorial party which finished some days ago. If you encounter any other issue or problem please post it as an issue in the appropiate repository. For this case it would be https://github.com/gazebosim/docs/issues. Thanks a lot for your active participation during the tutorial party!
