### ISSUE TITLE
gz-sim: grid.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#262]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/grid.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Output Images 

**_1. Change Horizontal line value_** 
![Screenshot from 2023-09-07 20-00-26](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/144ce8d2-e1a2-4acf-adca-a6b2c0cc80a3)
**_2. Change cell length_** 
![Screenshot from 2023-09-07 20-01-42](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/3d7484a9-0780-4548-a01c-5d850d354a2a)
**_3. Change colour of Grid_** 
![Screenshot from 2023-09-07 20-03-01](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/cd1daf59-1ff3-4d80-b20c-2022656cc831)
**_4. Change Orientation of Grid_** 
![Screenshot from 2023-09-07 20-05-18](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/9598d5c6-2b9f-4041-b1c5-1f6fe94bc0fe)

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
