### ISSUE TITLE
gz-sim: Headless Rendering

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#266]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/headless_rendering.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/headless_rendering.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by AndrejOrsula** [comment]
[Partial test - skipped AWS Example]

> Note: I tried this locally inside `headless` Docker, so the test method might be flawed (not a proper headless server)

Headless rendering works locally inside a Docker container under these configs (different `docker run ...` opts/args):
- with X11 | without X11 support
  - with: `.xauth` file with relevant volumes (e.g. `/tmp/.X11-unix`) and envs (e.g. `DISPLAY`) 
  - without: nothing (gz client does not work under this condition - as expected)
- with NVIDIA GPU | with integrated Intel GPU
  - NVIDIA: configured NVIDIA Container Toolkit and `--gpus all`
  - Intel: `--device=/dev/dri:/dev/dri --group-add video` (not exactly sure about this one)

Tested by running `gz sim -v 4 -s -r --headless-rendering sensors_demo.sdf`, and sensor data gets generated (checked via `gz topic -e -t <topic>` for `/camera`, `/depth_camera` and `/lidar`).

**Comment by Voldivh** [comment]
This looks good to me thanks @AndrejOrsula
