### ISSUE TITLE
gz-sim: heightmap.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#267]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/heightmap.sdf)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Hello!

The world loads with no issue. Although, for me it wasn't clear how to to the heighmap, as the world just point to a fuel model which I could not find. Apperently I was not the first one to have doubts on this, as you can see in this thread:

https://answers.gazebosim.org//question/28523/how-to-use-heightmaps-with-gazebo-garden/

Is there an .sdf with a better description of the height map part?

**Comment by azeey** [comment]
[This](https://app.gazebosim.org/chapulina/fuel/models/Heightmap%20Bowl) is the model on Fuel. You can download the model from there and inspect it if you'd like. There's a similar file in the gz-sim source (https://github.com/gazebosim/gz-sim/blob/4135cd1874ff20ff67d2c37995b9a0c5f4d459fb/test/worlds/heightmap.sdf.in) , but you'll have to replace `@CMAKE_SOURCE_DIR@` yourself. Apart from that, I don't think we have a tutorial for how to create heightmaps in gz-sim. Even though it's a Gazebo-classic documentation [this](https://classic.gazebosim.org/tutorials?tut=dem&cat=build_world) might be a good starting point.

I think we can go ahead and close this issue though since the world loads fine.

**Comment by matosinho** [comment]
Thank you!
