### ISSUE TITLE
gz-sim: Importing a Mesh to Fuel

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#269]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/meshtofuel.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/mesh_to_fuel.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Under the code section in "Include the model in a world", there seems to be some invalid characters (highlighted in red).
<img width="1025" alt="Screenshot 2023-09-08 at 9 30 58 PM" src="https://github.com/gazebosim/gazebo_test_cases/assets/29516177/575e90e1-78fb-4aa4-849a-bfd69f82d0c1">

**Comment by JACOBIN-SCTCS** [comment]
Will check the remaining steps and report

**Comment by JACOBIN-SCTCS** [comment]
The remaining things are working in Gazebo Harmonic (Including model working in Binary version of Gazebo)

![fuel](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/c658966c-7b59-4636-9d07-f2a4ec914f52)
![fuel_upload_test](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/d4429065-b3fa-4f6a-8f97-0656714165c4)


The onl

**Comment by Voldivh** [comment]
> Under the code section in "Include the model in a world", there seems to be some invalid characters (highlighted in red).

Yeah, this issue seems to be happening in couple of places, we are looking into it. Thanks @JACOBIN-SCTCS

**Comment by azeey** [comment]
This is fixed by https://github.com/gazebosim/docs/pull/388
