### ISSUE TITLE
gz-sim: joint_controller.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#273]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/joint_controller.sdf)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
Related PR https://github.com/gazebosim/gz-sim/pull/2144
