### ISSUE TITLE
gz-sim: kinetic_energy_monitor.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#276]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/kinetic_energy_monitor.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Here's the output images 

![gz_linect](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/72817269-5923-4d45-a6b4-500c8890e5a2)
![gz_sim_kinectic_value](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/02351bf0-bafd-4225-9762-71cb6b55c808)

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
