### ISSUE TITLE
gz-sim: levels.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#280]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/levels.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Works , as per the instruction.

**_1. Initial stage_**
![Screenshot from 2023-09-07 16-59-35](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/42acc373-bf14-4a44-ad7c-2f2d7b5d94df)

**_2. levels unload as per robot proximity_**  
![Screenshot from 2023-09-07 17-00-42](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/0487f153-86ac-4848-82bd-d2abf1052c98)
![Screenshot from 2023-09-07 17-00-55](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/4aae7072-e8c9-47f4-bd37-b5bda53c7698)
![Screenshot from 2023-09-07 17-01-43](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/e5f735a4-7201-441a-8416-829c19b27d05)

**Comment by mjcarroll** [comment]
Thanks!
