### ISSUE TITLE
gz-sim: lift_drag.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#283]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/lift_drag.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Working , as expected


https://github.com/gazebosim/gazebo_test_cases/assets/96059006/6ed7700c-1e14-4ba3-af54-d65affba624f

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
