### ISSUE TITLE
gz-sim: lightmap.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#286]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/lightmap.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
**_Output image_** 

![lightmap](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/484b699f-fdbb-4d2e-98c1-a6741be369e5)
