### ISSUE TITLE
gz-sim: lights.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#287]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/lights.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Here's the output 

**_1. In absence of  Directional lights_**
![Screenshot from 2023-09-07 18-50-51](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/a0c90a1c-5b43-403c-aa1f-d127b429680e)

**_2. With Directional lights_** 
![Screenshot from 2023-09-07 18-50-32](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/485b3d5d-b943-4c48-968f-996a919c79b9)

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
