### ISSUE TITLE
gz-sim: linear_battery_demo.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#288]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/linear_battery_demo.sdf)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by j-rivero** [comment]
https://github.com/gazebosim/gz-sim/issues/2146
