### ISSUE TITLE
gz-sim: log_record_dbl_pendulum.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#289]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/log_record_dbl_pendulum.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Here's the ouput video , it works fine .

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/ed2e0661-679a-4e29-9479-0c23b3d01127

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
