### ISSUE TITLE
gz-sim: log_record_resources.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#291]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/log_record_resources.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working in Binary Installation of Gazebo Harmonic.


The log files directory is successfully created 
![log_dir](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/60314ad6-2dbb-41fd-938a-38093edfba46)

The -v tags are also working fine
![log_verbose](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/2879ae8d-65d6-46ba-979d-70962271985a)


The playback as well as simulation is also working fine.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/20d83f24-fc8e-4c16-b85d-ebc19342e960

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS
