### ISSUE TITLE
gz-sim: log_record_shapes.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#292]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/log_record_shapes.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Working, as expected .

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/484d37b7-3466-4a0a-8e10-f1bc9f7a102f

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
