### ISSUE TITLE
docs: actors

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#3]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/actors)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/actors.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by mjcarroll** [comment]
LGTM, one nit: https://github.com/gazebosim/docs/pull/385
