### ISSUE TITLE
gz-sim: mimic_fast_slow_pendulums_world.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#319]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/mimic_fast_slow_pendulums_world.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Getting this error

```
[Err] [Physics.cc:1725] Attempting to create a mimic constraint for joint [slow_joint] but the chosen physics engine does not support mimic constraints, so no constraint will be created.
```
![Screenshot from 2023-09-11 21-57-40](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/8441e986-5a5c-4db4-975b-f0eadbd6126e)

**Comment by azeey** [comment]
This requires using bullet-featherstone. The  instructions to run should be in the `.sdf` file.

**Comment by jchaudhary21** [comment]
Yeah, right, I missed with this command:

```
--physics-engine gz-physics-bullet-featherstone-plugin
```
After running this command, now it's working fine.
Thank you @azeey  for pointing this out , and apologize for any inconvenience.

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/54f6c5d0-9ab4-402e-8882-acc34ebd8a00

**Comment by azeey** [comment]
@jchaudhary21 no need for apologies 🙂 . Thanks for testing it out!
