### ISSUE TITLE
docs: spawn_urdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#32]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/spawn_urdf)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/spawn_urdf.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The steps are working in Binary Installation of Gazebo Harmonic.


https://github.com/gazebosim/gazebo_test_cases/assets/29516177/d3227efc-8293-4d28-a0d9-f091186c39e1

I highlight some problems in the documentation provided.

![rrbot](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/8ddfe30c-f22d-4361-b71c-286848693e7f)

The link 'rrbot.urdf' isnt linked to a valid page. The link 'this tutorial' points to ROS2 Foxy documentation page which has reached End Of Life

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS I'll create a PR to fix broken links
