### ISSUE TITLE
gz-sim: Model Command

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#324]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/model_command.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/model_command.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
**Everything works alright I just noticed some differences in the syntax:**

- Intertial Pose also has RYP values:
  Live version:
  ```
  - Inertial Pose:
     [0.000000 | 0.000000 | 0.000000] 
  ```
  In Harmonic:
  ```
   - Inertial Pose [ XYZ (m) ] [ RPY (rad) ]:
      [0.000000 0.000000 0.000000]
      [0.000000 -0.000000 0.000000]
  ```

- Joints values:
  Live version:
  ```
  - Joint [23]
      - Name: caster_wheel
      - Parent: vehicle_blue [8]
      - Type:  ball
      - Parent Link: caster
      - Child Link:  chassis
      - Pose [ XYZ (m) ] [ RPY (rad) ]:
          [0.000000 | 0.000000 | 0.000000]
          [0.000000 | -0.000000 | 0.000000]
  ```
  
  In Harmonic:
  ```
  - Joint [23]
    - Name: caster_wheel
    - Parent: vehicle_blue [8]
    - Type: ball
    - Parent Link: chassis [9]
    - Child Link: caster [18]
    - Pose [ XYZ (m) ] [ RPY (rad) ]:
      [0.000000 0.000000 0.000000]
      [0.000000 -0.000000 0.000000]
  ```

**Comment by Voldivh** [comment]
Thanks @Kartik9250
