### ISSUE TITLE
gz-sim: Model Photo Shoot

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#326]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/model_photo_shoot.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/model_photo_shoot.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
- Only these 5 images were saved. 
![1](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/a54d91d2-caca-4ef4-a7da-20c79335c30a)
![2](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/a3293cf5-5a06-4c8e-91b4-37d2e4b47fa1)
![3](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/9d3e45f8-78ef-4b63-b87b-c4a805d83a46)
![4](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/d5b837e4-8536-4da2-8aee-3c591d6fd3e2)
![5](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/c37d40e9-01cf-480b-a55b-7a85cefaf795)

- Poses.txt include this:
```
Translation: -0.00212611 0.0249624 0.835096
Scaling: 0.412604
```

- Also the sim is all white.
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/16337305-cbaf-42fa-a067-fad74b5d8148)
