### ISSUE TITLE
gz-sim: model_photo_shoot.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#327]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/model_photo_shoot.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
I am getting the following 5 pictures of robonaut as output which is expected.

![1](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/ec114fd8-0ba7-4e89-86ef-a46c3dcce62d)
![2](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/f75d63c1-aefa-4aff-ac4a-42b3ac95a16d)
![3](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/57045765-d2b9-43a0-8fa0-52cdf6b474a9)
![4](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/6e765e21-72f0-4437-8812-09b16efbc393)
![5](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/88bc4661-9d1f-4374-8190-12abee95fdda)

However the simulation seems to be empty. Is this the expected outcome ?
![Screenshot_2023-09-09_18-23-07](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/fe16dd18-d34b-4131-8139-ec20aa578c96)

**Comment by Voldivh** [comment]
Could you take a look @azeey?

**Comment by ahcorde** [comment]
you should include 

```xml
   <plugin
        filename="gz-sim-scene-broadcaster-system"
        name="gz::sim::systems::SceneBroadcaster">
    </plugin>
```

but I think you should run this with this command:

```bash
gz sim  -s -r -v 4 \-\-iterations 50 model_photo_shoot.sdf
```

The gui will close very fast, there is no need to include the 3D scene

**Comment by azeey** [comment]
Agree with @ahcorde. The example is meant to generate the pictures and exit. The instructions @ahcorde  mentioned are in the `.sdf` file.

**Comment by azeey** [comment]
Will go ahead and close this since the instructions work.
