### ISSUE TITLE
gz-sim: Mouse Drag

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#328]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/mouse_drag.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/mouse_drag.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Works perfectly! No issues at all! Very cool plugin to play with, I'm definetly using to test station keeping of robots.

Here is a gif of me having fun:
![mouse_drag](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/83dcaff0-9f92-4a94-85a9-88014ee7283c)

If any additional test is needed, let me know.

**Comment by Voldivh** [comment]
Thanks @matosinho
