### ISSUE TITLE
gz-sim: Mouse Drag

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#329]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/mouse_drag.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/mouse_drag.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
I would like to work on this ticket

**Comment by Kartik9250** [comment]
Plugin works alright
![ezgif com-video-to-gif (1)](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/8f5e1401-a4f8-4ca8-8de8-acba4b541968)

**Comment by Voldivh** [comment]
Thanks @Kartik9250
