### ISSUE TITLE
gz-sim: Move Camera to model

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#330]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/move_camera_to_model.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/move_camera_to_model.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Shouldnt  **ign** in the command 
`ign service  -s /gui/move_to/model --reqtype gz.msgs.GUICamera  --reptype gz.msgs.Boolean -r 'name: "box", pose: {position: {z:5}, orientation: {x:0, y:0, z: -1, w:0}}, projection_type: "orbit"' --timeout 5000
`
be replaced with gz (I am not sure of this).


Also upon running
`ign service  -s /gui/move_to/model --reqtype gz.msgs.GUICamera  --reptype gz.msgs.Boolean -r 'name: "box", pose: {position: {z:5}, orientation: {x:0, y:0, z: -1, w:0}}, projection_type: "orbit"' --timeout 5000`
 I get Service call failed (Attaching screenshot).

![service_error](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/55fd8ec2-51bb-4adb-b8af-15772eb8ae89)

The service is present when I tried to list all the services (Attaching screenshot)
![service_list](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/b5191dee-7d79-4e2a-9ad1-0369c84e59b3)

The world that I used is  'shapes.sdf'

**Comment by iche033** [comment]
https://github.com/gazebosim/gz-sim/pull/2126
