### ISSUE TITLE
gz-sim: Move Camera to model

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#331]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/move_camera_to_model.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/move_camera_to_model.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
I would like to work on this ticket

**Comment by Kartik9250** [comment]
I tried the instructions. Camera position is not being changed. Error while using the service: `[GUI] [Err] [ViewAngle.cc:345] Failed to get gazebo-entity user data [box]`
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/6fd47e9d-d843-4d29-98bf-d8c346945ae3)
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/51cb0ca4-bc69-432d-b6f0-051c8c112211)

**Comment by iche033** [comment]
someone noticed this as well. https://github.com/gazebosim/gz-sim/pull/2126 should fix the issue.

**Comment by azeey** [comment]
@Kartik9250 can you update gz-sim and check again?

**Comment by Kartik9250** [comment]
@azeey @Voldivh 
Still its not working.
I forgot to mention that on the Live site it instead `ign` it should be `gz`

![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/82f8838c-ca68-481f-a07e-d0020eed38ed)
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/d989c227-3f34-4995-b34a-2399fd5560da)
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/a7a01245-70f8-4e25-aeb0-9b1881bdcfc5)
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/65026970-dddc-4db6-a790-129a302e1850)

**Comment by iche033** [comment]
oh that fix is targeted at garden. We'll to merge forward to harmonic
