### ISSUE TITLE
gz-sim: multi_lrauv_race.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#332]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/multi_lrauv_race.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Hello! 

Unfortunately I'm not sure if I'm getting the expected results. I'm ran `gz sim multi_lrauv_race.sdf` on the terminal and the following screen popped up:
![image](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/3b820ba2-5ee7-43b8-8c20-e6af8cf91183)

Although, when I click play a very strange behaviour happened:
![multi_auv_strange](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/5bf7fea6-55cb-4d33-8cbb-4afcdb5a22b8)

My CPU/GPU/Memory usage were also all lower than 40%.

Also, when I launched the world the following error messages appeared, I dunno if it is correlated:
```
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
```

Please let me know if I should do any additional testing.

**Comment by iche033** [comment]
yes it's affecting others as well. There is a pull request to fix the issue: https://github.com/gazebosim/gz-sim/pull/2111

**Comment by matosinho** [comment]
How can I test the pull request with binary install? I'm planning to go for source install later and I could definetely test, but for binary I dunno how to do it.

**Comment by Voldivh** [comment]
I would say to test it out with the source install. As far as I know, there shouldn't be any other way to try out a PR.

**Comment by Voldivh** [comment]
Hey @matosinho did you manage to try out the fix from the PR?

**Comment by matosinho** [comment]
Not yet... Since the mentioned pull request to fix was accept, if I re download the binaries, I should be able to get the version with the implemented PR, correct?

**Comment by azeey** [comment]
No, we haven't released binaries for gz-sim yet. You'd have to build from source or wait till we make another release.

**Comment by Voldivh** [comment]
I tried out the fix and works just fine. Since the PR have been merged, I'll be closing this issue.
