### ISSUE TITLE
gz-sim: particle_emitter.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#339]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/particle_emitter.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
**Getting errors** 

```
[Err] [Physics.cc:2889] Internal error: a physics entity ptr with an ID of [9] does not exist.
[Err] [Physics.cc:2889] Internal error: a physics entity ptr with an ID of [7] does not exist.
```

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/2c625a53-5a8d-41be-99a1-b4669ee414b1
