### ISSUE TITLE
gz-sim: pendulum_links.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#340]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/pendulum_links.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Hello! 

All seems well! Here is a gif of the example:
![pendulum](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/c9cbd1f3-41cb-4a4b-9546-fc10e920e546)

I reduced a bit the angle speed, it was too fast the suggestion of the tutorial.

If any additional test is needed, let me know!
