### ISSUE TITLE
gz-sim: performer_detector.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#342]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/performer_detector.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Working , as expected .

![Screenshot from 2023-09-11 21-12-16](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/1f92d764-98fe-4042-be45-46c4bd3ec1fe)

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
