### ISSUE TITLE
gz-sim: Physics engines

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#343]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/physics.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/physics.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by mjcarroll** [comment]
I think we could add a note about bullet/featherstone for completeness here. https://github.com/gazebosim/gz-sim/pull/2143

**Comment by Voldivh** [comment]
Closing this since PR have been merged.
