### ISSUE TITLE
gz-sim: physics_options.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#345]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/physics_options.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Output Video

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/4e5939e7-019e-4c7f-b71c-eff1e34a2035

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
