### ISSUE TITLE
gz-sim: plane_propeller_demo.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#346]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/plane_propeller_demo.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
working, as expected 

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/d9b7809b-c9df-4a14-b246-68e3d802ac46

**Comment by Voldivh** [comment]
Thanks @jchaudhary21
