### ISSUE TITLE
gz-sim: plot_3d.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#347]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/plot_3d.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working for Gazebo Harmonic. The "Reset Simulation" button works but is partially hidden.
https://github.com/gazebosim/gazebo_test_cases/assets/29516177/88a7e89a-cadb-4f63-acf8-7ce2adfa3079

**Comment by JACOBIN-SCTCS** [comment]
Working for Gazebo Harmonic. The "Reset Simulation" button works but is partially hidden.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/e9740b84-fc99-472a-8a9f-3a80fa514861

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS, noted the partial reset button.
