### ISSUE TITLE
gz-sim: pose_publisher.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#349]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/pose_publisher.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
Just a question, this has binary label but only source weblink in hte description. So which installation version should be used for testing?

**Comment by JACOBIN-SCTCS** [comment]
Working on Binary installation of Gazebo Harmonic

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/b9cd1441-0e5c-405c-8552-927d9f73200d

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS
