### ISSUE TITLE
gz-sim: projector.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#350]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/projector.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by VeronikaBojt** [comment]
Tested launching this world:
![view](https://github.com/gazebosim/gazebo_test_cases/assets/74018563/d437a6c5-c167-435d-9a4a-79dbaa1187da)


It seems to load correctly, but only a portion of the reset button is visible.

**Comment by Voldivh** [comment]
Thanks @VeronikaBojt, the issue with the reset button is happening along several tutorials (currently looking into it), so don't worry about it. I'll be closing this issue as completed.
