### ISSUE TITLE
gz-sim: Python interfaces

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#351]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/python_interfaces.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/python_interfaces.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by mjcarroll** [comment]
I believe the following only works with a `merge-install` with colcon, correct?  We are advising to do that iirc, but could still be overlooked.

```
export PYTHONPATH=$PYTHONPATH:<path to ws>/install/lib/python
```

**Comment by mjcarroll** [comment]
My output looks slightly different.  @azeey is this just a difference in computers or has something actually changed in the way that the python thing works:

[Msg] Loading SDF world file[/home/ahcorde/gz_fortress/src/ign-gazebo/examples/scripts/python_api/gravity.sdf].
[Dbg] [Physics.cc:789] Loaded [gz::physics::dartsim::Plugin] from library [/home/ahcorde/gz_fortress/install/lib/gz-physics-5/engine-plugins/libgz-physics-dartsim-plugin.so]
[Dbg] [SimulationRunner.cc:909] Loaded system [gz::sim::systems::Physics] for entity [1]
[Msg] Loaded level [3]
[Msg] Serving world controls on [/world/gravity/control], [/world/gravity/control/state] and [/world/gravity/playback/control]
[Msg] Serving GUI information on [/world/gravity/gui/info]
[Msg] World [gravity] initialized with [default_physics] physics profile.
[Msg] Serving world SDF generation service on [/world/gravity/generate_world_sdf]
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource paths published on [/gazebo/resource_paths].
[Msg] Found no publishers on /stats, adding root stats topic
[Msg] Found no publishers on /clock, adding root clock topic
[Dbg] [SimulationRunner.cc:524] Creating PostUpdate worker threads: 2
[Dbg] [SimulationRunner.cc:537] Creating postupdate worker thread (0)
AddSystem1
World entity is  1
Gravity  0 0 -9.8
Entity for falling model is:  4
AddSystem2
iterations  1000
post_iterations  1000
pre_iterations  1000

**Comment by azeey** [comment]
`testFixture.py`  is not using python system plugins. It's using the python bindings for the `TestFixture` class. I'm guessing it's just an out-of-order printing issue. I get the same output as you on both Harmonic and Garden.

**Comment by mjcarroll** [comment]
Should we update the output to match or is this fine?

**Comment by azeey** [comment]
I tried it on two different computers and got the python messages after the last "postupdate worker thread" message, so maybe we should change it.

**Comment by azeey** [comment]
https://github.com/gazebosim/gz-sim/pull/2157

**Comment by Voldivh** [comment]
Closing this since PR have been merged.
