### ISSUE TITLE
gz-sim: python_system_loader.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#353]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/python_system_loader.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
Propesed fix https://github.com/gazebosim/gz-sim/pull/2123

there is a trace in the terminal, that I can't understand:

```{.sh}
69 0:00:04.843875 pre_update
69 0:00:07.878767 pre_update
69 0:00:10.911406 pre_update
69 0:00:13.942802 pre_update
69 0:00:16.975978 pre_update
```
