### ISSUE TITLE
gz-sim: quadcopter.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#354]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/quadcopter.sdf)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The functionality is working. Sometimes I had to type the same command multiple times before the quadcopter could actually lift off (Beginning parts of video). Other than that the functionality is working perfectly.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/fcde4e6c-db98-45f9-b6ae-aead5e8a00da

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS, closing this as completed.
