### ISSUE TITLE
gz-sim: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#356]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/libs/sim)
- [Source](https://github.com/gazebosim/gz-sim/blob/gz-sim8/README.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
I installed sim from source, docs works

**Comment by Voldivh** [comment]
Thanks @Kartik9250
