### ISSUE TITLE
gz-sim: Rendering plugins

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#358]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/rendering_plugins.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/rendering_plugins.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by iche033** [comment]
links are fixed in https://github.com/gazebosim/gz-sim/pull/2107. Everything else looks good to me.
