### ISSUE TITLE
gz-sim: rolling_shapes.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#363]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/rolling_shapes.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Output video 
 
[rolling_sdf.webm](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/72543444-d1b7-4515-a4b4-448e01e4653d)

- [x]  Instructions work
- [x]  Video
