### ISSUE TITLE
gz-sim: sensors_demo.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#365]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/sensors_demo.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working on Gazebo Harmonic. A warning message also appears of which I am attaching a screenshot

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/002839db-389b-416e-9bfa-cf9ece2ab1f0
![warning](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/679bd842-af8c-4387-8145-44136ba17ec3)

**Comment by JACOBIN-SCTCS** [comment]
Working on Gazebo Harmonic. There was a warning whose screenshot I am also attaching

Uploading sensors_demo-2023-09-07_20.05.42.mp4…

**Comment by JACOBIN-SCTCS** [comment]
Working on Gazebo Harmonic. There was a warning whose screenshot I am also attaching.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/a4f51503-c996-4cce-9390-e800bdc95eb8

**Comment by ahcorde** [comment]
Fixed warning https://github.com/gazebosim/gz-sim/pull/2122
