### ISSUE TITLE
gz-sim: sensors.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#366]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/sensors.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
**Run this SDF file , get the sensor values as per instructions .**
![Screenshot from 2023-09-07 13-43-32](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/2977d2a4-3f9a-4255-8f17-52ee2fa5be39)

**But along with that a small warning message  also appears  on terminal** 
![Screenshot from 2023-09-07 13-41-10](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/8c097cac-6ab9-4e07-8927-f653bb39726b)




 ```
Warning [Utils.cc:130] [/sdf/world[@name="sensors"]/model[@name="force_torque_demo"]/link[@name="base_plate"]/static:/home/jc/Downloads/sensors.sdf:L209]: XML Element[static], child of element[link], not defined in SDF. Copying[static] as children of [link].

```

 ```
Warning [Utils.cc:130] [/sdf/model[@name="force_torque_demo"]/link[@name="base_plate"]/static:<data-string>:L3]: XML Element[static], child of element[link], not defined in SDF. Copying[static] as children of [link].```

**Comment by Voldivh** [comment]
Thanks @jchaudhary21 I'll take note of the warning message. Closing this issue as completed for now.
