### ISSUE TITLE
gz-sim: shapes_bitmask.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#370]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/shapes_bitmask.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Here's the instruction 
`Which means that green and red can't collide with each other, but they both collide with yellow. Move them around to see it working! `

**Output Images** : 
_1. Red and Yellow box, not colliding_ 
![Screenshot from 2023-09-07 17-59-10](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/0edd4e04-354f-46ae-8e2b-e7e41d0b8173)

_2.  Green and Red box, colliding_
![Screenshot from 2023-09-07 18-01-43](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/f75eeb21-3afe-4af9-98b0-16ba38947b66)

_3.  Green and Yellow box, colliding_
![Screenshot from 2023-09-07 18-02-07](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/f6984a04-c31e-42e4-8cf9-ff139d912e37)

**Comment by ahcorde** [comment]
I can reproduce the expected behaviour, @jchaudhary21 can you provide more details

https://github.com/gazebosim/gazebo_test_cases/assets/1933907/1d4164bc-088b-40fc-adcc-fdd09bb86d59

**Comment by Voldivh** [comment]
I was also able to reproduce the expected behavior.

**Comment by jchaudhary21** [comment]
I apologize for my previous comment. I believe I wrote it incorrectly.
**This simulation is working perfectly fine.** I was simply trying to write whatever was mentioned in the instructions. I was also able to reproduce the expected behavior.

**Comment by Voldivh** [comment]
Thanks @jchaudhary21, don't worry about it :D glad it is working for you as well.
