### ISSUE TITLE
gz-sim: shapes.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#371]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/shapes.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working on Binary Installation of Gazebo Harmonic.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/4c79376c-07fc-49f3-80b4-4d5c473ea40b

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS
