### ISSUE TITLE
gz-sim: spaces.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#374]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/spaces.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Worked on this test case 
Run the given SDF fle and here's the output 
![SDF_with_spaces_ss](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/148649c2-2213-4012-a4d8-23edae7740b0)

But on terminal getting this warning !!
```Service [world/world with spaces/get_parameter] is not valid.
Service [world/world with spaces/list_parameters] is not valid.
Service [world/world with spaces/set_parameter] is not valid.
Service [world/world with spaces/declare_parameter] is not valid.
Service [/world/world with spaces/set_pose_vector] is not valid.
Service [/world/world with spaces/visual_config] is not valid.
```

![SDF_with_spaces_terminal_ss](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/1255f312-3174-4559-9b6b-c9327ff160bd)

And whenever I tried to run the simulation `Service [/world/world with spaces/control/state] is not valid.` this warning message appears.

**Comment by Voldivh** [comment]
Thanks @jchaudhary21 I'll take a look into the warnings and service issues.

**Comment by ahcorde** [comment]
proposed a fix https://github.com/gazebosim/gz-sim/pull/2121
