### ISSUE TITLE
gz-sim: Spherical coordinates

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#376]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/spherical_coordinates.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/spherical_coordinates.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
Hey, I would like to work on this ticket

**Comment by Kartik9250** [comment]
- **spherical_coordinates.sdf**
    Only one black cube appears in the center. When I try to Play the sim one error saying `[GUI] [Err] [Conversions.cc:1118] Attempting to convert a NavSat SDF sensor, but the sensor pointer is null.`
    ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/73454c5d-2326-4821-9e57-b617a4ad27c1)


- **dem_moon.sdf**
    ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/8dc7485e-c594-4d44-ba06-ac9e4037b936)
    Can I not change the coordinates in the `dem_moon.sdf`
    
    
- **Service:**
    - Spherical coordinates are values are being changed, checked via sim spherical coordinate values.
        ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/91f72ec3-2b55-4a02-a87f-2d91c58bff57)

    - Creating entities: Works, one error does pops up:`[Err] [UserCommands.cc:1226] HasSphericalCoordinates`
        ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/36357d2b-e40d-4b6b-bb97-44d9a75309b7)
        
    - Moving entities: Works, but one error: `[Err] [UserCommands.cc:1568] Unable to update the pose for entity [0]: entity doesn't exist.` 
        ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/d22c40b2-2c59-4e2d-9178-498df65dae7d)
    
- Querying entities' coordinate: I didnt understand how I should test this.

**Comment by azeey** [comment]
https://github.com/gazebosim/gz-sim/issues/2163 has been reported regarding the first error.
