### ISSUE TITLE
gz-sim: spherical_coordinates.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#377]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/spherical_coordinates.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Voldivh** [comment]
Thanks @jchaudhary21 I'll take a look into it.
