### ISSUE TITLE
gz-sim: Terminology

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#379]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/terminology.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/terminology.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Bi0T1N** [comment]
The page has issues with non-working links but this is addressed in https://github.com/gazebosim/gz-sim/pull/2107.

**Comment by Voldivh** [comment]
Thanks for the feedback @Bi0T1N, I'll keep track of this issue after PR is merged
