### ISSUE TITLE
gz-sim: Test fixture

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#381]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/test_fixture.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/test_fixture.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
Both the `command_TEST` and `gravity_TEST` works as mentioned in the [examples/standalonne/gtest_setup](https://github.com/gazebosim/gz-sim/tree/main/examples/standalone/gtest_setup)
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/01b3bbaa-8f30-419c-a286-c42577ea27e4)
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/4f3c2a7a-c6ba-4056-8be2-94c95e8e871e)

**Comment by Voldivh** [comment]
Thanks @Kartik9250
