### ISSUE TITLE
gz-sim: tracked_vehicle_simple.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#385]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/tracked_vehicle_simple.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
This simulation isn't working when I tried it. The quadruped like vechicle didnt move while inputting teleop commands. Can somebody check

**Comment by Voldivh** [comment]
Sure, I'll take a look.

**Comment by Voldivh** [comment]
Yeah for me it didn't move with either the teleop keys or publishing to it's topic. I'll file a bug report. Thanks @JACOBIN-SCTCS

**Comment by ahcorde** [comment]
This example requires to install libdart13 or compile from source dart. This is not working out of the box. 

Related with this issue: https://github.com/gazebosim/gz-sim/issues/1662

Can we update dart ? @scpeters @azeey

**Comment by Voldivh** [comment]
> This example requires to install libdart13 or compile from source dart. This is not working out of the box.
Oh ok, I wasn't aware, thanks @ahcorde

**Comment by scpeters** [comment]
I've replied in https://github.com/gazebosim/gazebo_test_cases/issues/224#issuecomment-1710658799

**Comment by azeey** [comment]
Closing since this being tracked in https://github.com/gazebosim/gz-sim/issues/1662
