### ISSUE TITLE
gz-sim: trajectory_follower.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#386]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/trajectory_follower.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working for Gazebo Harmonic. Attaching video

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/76d68b22-d554-4b11-b208-90154269dd3e

**Comment by Voldivh** [comment]
Thanks! Closing this as completed.
