### ISSUE TITLE
gz-sim: Triggered Publisher

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#387]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/triggeredpublisher.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/triggered_publisher.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
https://github.com/gazebosim/gz-sim/pull/2130

When I click reset the triggers are not resseted. Looking into it

**Comment by ahcorde** [comment]
https://github.com/gazebosim/gz-sim/pull/2132

**Comment by ahcorde** [comment]
I think we should include the reset method in the `TriggeredPublisher` plugin too

**Comment by azeey** [comment]
Closing since a PR has been opened
