### ISSUE TITLE
gz-sim: Triggered Publisher

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#388]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/triggeredpublisher.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/triggered_publisher.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
Hey, I would like to work on this ticket

**Comment by Kartik9250** [comment]
I tried running the world file. I just found one issue the vehicle does not seems to stop and reset its position after both of the boxes fall.

**Comment by Voldivh** [comment]
Thanks @Kartik9250 could you perhaps provide an image/video to understand a little bit better the issue you are getting?

**Comment by Kartik9250** [comment]
@Voldivh My appologies for the delay

![ezgif com-video-to-gif (3)](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/592166c4-2305-43d2-86b3-93aac98bfd47)

- Earlier I thought the `blue_vehicle` was supposed to reset it's pose and cmd_vel by itself once both the boxes drop on the `ground_plane`. I Later figured out that I was supposed to publish an empty message on the `reset_robot` topic. I think this should be mentioned in the documentation.

- Some things noticed were:
    - I got the following messages:
        ```
        Msg [NameManager::issueNewName] (Skeleton::Joint | trigger) The name [fixed] is a duplicate, so it has been renamed to [fixed(1)]
        Msg [NameManager::issueNewName] (Skeleton::N4dart8dynamics9ShapeNodeE | trigger) The name [box_body:c1] is a duplicate, so it has been renamed to [box_body:c1(1)]
        ```
    - The last section in the [documentation](https://gazebosim.org/api/sim/8/triggeredpublisher.html) `Once both boxes have fallen, we can publish a message to invoke a service call to reset the robot position  ...more` is repeated twice.

**Comment by iche033** [comment]
https://github.com/gazebosim/gz-sim/pull/2150 removes the duplication section and adds explicit instruction to reset robot pose

**Comment by Voldivh** [comment]
Thanks for testing it out @Kartik9250. The warning messages you are receiving are basically because of the names used on the `box_2` that are the same for `box_1`, and also that is is using the same plugin for the trigger for both boxes instead of a trigger individually for each box.  I'll be closing this issue since @iche033 PR with the modifications have been merged and the instructions work as expected.
