### ISSUE TITLE
gz-sim: triggered_camera_sensor.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#389]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/triggered_camera_sensor.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working for Binary Installation of Gazebo Harmonic. Seems like there is  a bug in the way  in which the "Reset Simulation" button is displayed.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/4a3e85d9-6522-470d-9957-1f6078a5fc07

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS I'll take note of the visual bug.
