### ISSUE TITLE
gz-sim: trisphere_cycle_wheel_slip.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#391]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/trisphere_cycle_wheel_slip.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working in Binary installation of Gazebo Harmonic.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/efcf5008-6c36-40be-9247-a0759683d11d
