### ISSUE TITLE
gz-sim: tunnel.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#392]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/tunnel.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
**_Getting Warnings and Errors_** 

1.  WARNINGS  
![Screenshot from 2023-09-09 20-48-20](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/7b88e5ba-dbeb-4e7d-b57f-368c846261f9)

```
Warning [Utils.cc:130] [/sdf/world[@name="diff_drive"]/model[@name="vehicle"]/link[@name="left_front_wheel_link"]/collision[@name="left_front_wheel_link_collision"]/surface/friction/ode/max_vel:/home/jc/Downloads/tunnel.sdf:L1301]: XML Element[max_vel], child of element[ode], not defined in SDF. Copying[max_vel] as children of [ode].
```


2. ERRORS
![Screenshot from 2023-09-09 20-49-48](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/33464531-a366-45ce-8dd0-c976f1b3470e)

```
Warning [Utils.cc:130] [/sdf/world[@name="diff_drive"]/model[@name="vehicle"]/link[@name="left_front_wheel_link"]/collision[@name="left_front_wheel_link_collision"]/surface/friction/ode/max_vel:/home/jc/Downloads/tunnel.sdf:L1301]: XML Element[max_vel], child of element[ode], not defined in SDF. Copying[max_vel] as children of [ode].
```

**Comment by azeey** [comment]
This looks like an issue with the use if ignitionrobotics.org URLs. The plan is to fix all the models on Fuel soon so they refer to gazebosim.org instead. We'll keep this open until then.
