### ISSUE TITLE
gz-sim: Underwater vehicles

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#393]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/sim/8/underwater_vehicles.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/underwater_vehicles.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by iche033** [comment]
thanks I created a PR to fix this in https://github.com/gazebosim/gz-sim/pull/2120

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS @iche033! I'll be closing this as completed since the PR have been merged.
