### ISSUE TITLE
gz-sim: Underwater vehicles

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#394]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/underwater_vehicles.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/underwater_vehicles.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
I tried launching the world it loaded alright, but none of the values that I published were showing any movements.
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/93c25026-67fc-4e27-975d-75d6fb3e8a73)

**Comment by ahcorde** [comment]
Hi @Kartik9250, thank you for testing this examples. Can you try these changes? 

https://github.com/gazebosim/gz-sim/pull/2128

**Comment by Kartik9250** [comment]
@ahcorde I tried the changes in https://github.com/gazebosim/gz-sim/pull/2128

I am able to control the auv. I just found the rudders a bit problematic, its not going to the specified position sometimes. Ocean currents is also working I just forgot to record it.
https://youtu.be/lWYonytfwvs

**Comment by Voldivh** [comment]
Thanks @Kartik9250 the video looks good to me. However, I would like confirmation that this is the expected behavior before closing this issue @ahcorde
