### ISSUE TITLE
gz-sim: velocity_control.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#395]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/velocity_control.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Output video

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/96ce27f1-6de4-408a-bed9-e4d2d71170ed


https://github.com/gazebosim/gazebo_test_cases/assets/96059006/69dba707-0166-45c4-99fb-619b6d3d8f85
