### ISSUE TITLE
gz-sim: Video Recorder

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#397]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/sim/8/videorecorder.html)
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/tutorials/video_recorder.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
I would like to work on this

**Comment by Kartik9250** [comment]
- I tried the video-recorder plugin and checked its configuration it worked just alright. (Added gif below)
    ![ezgif com-video-to-gif](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/1cb21429-5a11-49f7-a302-f39468f0da17)

- Though I was unable to test the hardware-accelerated encoding.

**Comment by Voldivh** [comment]
> Though I was unable to test the hardware-accelerated encoding.

Did you encounter an error?

**Comment by Kartik9250** [comment]
> > Though I was unable to test the hardware-accelerated encoding.
> 
> Did you encounter an error? @Kartik9250 

No, I just didn't understand how to set it up

**Comment by Voldivh** [comment]
Very well, thanks @Kartik925 closing this as completed
