### ISSUE TITLE
gz-sim: video_record_dbl_pendulum.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#398]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/video_record_dbl_pendulum.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Worked on this test case.
And here's the output video .

https://github.com/gazebosim/gazebo_test_cases/assets/96059006/9816b281-4e3e-4128-8ac2-41396ca36d0a

**Comment by Voldivh** [comment]
Thanks @jchaudhary21, closing this as completed.
