### ISSUE TITLE
gz-sim: visibility.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#399]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/visibility.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment]
Run the given SDF File and here's the output .
Output as per instructions mention in SDF file . 
![visibility](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/1a9b35b6-b99c-4d4b-9b93-3e5025297716)

**Comment by Voldivh** [comment]
Thanks @jchaudhary21, closing this as completed.

**Comment by ahcorde** [comment]
@iche033 I can see the shadow of the objects, is this correct ?

**Comment by iche033** [comment]
in ogre2 shadows are visible for objects with transparency. We should probably disable that and keep the behavior consistent with ogre1. So something that needs to be fixed.

**Comment by azeey** [comment]
Hi @jchaudhary21, congratulations! You are one of our top contributors in the Harmonic tutorial party. Can you send your email address to `addisu@openrobotics.org`  so we can send you the Harmonic t-shirt?
