### ISSUE TITLE
gz-sim: visualize_contacts.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#400]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/visualize_contacts.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working on Gazebo Harmonic.

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/328eb6fd-e649-4eb1-b9a9-cd2b61ea14cc

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS, closing this as completed.
