### ISSUE TITLE
gz-sim: visualize_lidar.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#401]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/visualize_lidar.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working on Gazebo Harmonic. Attaching video 

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/00480a09-3f75-497f-9169-8b58d53256c0

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS, closing this as completed.
