### ISSUE TITLE
gz-sim: wide_angle_camera.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#402]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/wide_angle_camera.sdf)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jmackay2** [comment]
I had no issues with `wide_angle_camera.sdf`.

- [x] Instructions work
- [x] Images match the result.

**Comment by Voldivh** [comment]
Thanks @jmackay2
