### ISSUE TITLE
gz-sim: wind.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#403]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/wind.sdf)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Tested to be working in Gazebo Harmonic. 

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/c7fdd99c-b755-4cdf-806c-ded4f422a331

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS, closing this as completed!
