### ISSUE TITLE
gz-sim: world_joint.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#404]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/world_joint.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Working in Gazebo Harmonic. Attaching video.


https://github.com/gazebosim/gazebo_test_cases/assets/29516177/262efdd3-a7bc-44e6-b9e4-02f741fbe001

**Comment by Voldivh** [comment]
Thanks @JACOBIN-SCTCS, closing this as completed.
