### ISSUE TITLE
gz-tools: Installation

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#405]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/tools/2/install.html)
- [Source](https://github.com/gazebosim/gz-tools/tree/gz-tools2/tutorials/install.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by mjcarroll** [comment]
LGTM, no change from Garden.
