### ISSUE TITLE
gz-tools: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#407]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/libs/tools)
- [Source](https://github.com/gazebosim/gz-tools/blob/gz-tools2/README.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Is the link under the Install heading correct ?. It points to the homepage of gazebo sim

**Comment by Voldivh** [comment]
It seems we are having some issues with the latest links for some of the packages. You can try to run the following command in order to install it:
`sudo apt install libgz-tools2-dev`

**Comment by JACOBIN-SCTCS** [comment]
> 
Working as expected.
![libgz](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/73cec1a2-4dc6-4902-8571-27d7b40e7afc)
