### ISSUE TITLE
gz-tools: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#408]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/libs/tools)
- [Source](https://github.com/gazebosim/gz-tools/blob/gz-tools2/README.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Same problem as in issue #407

**Comment by Voldivh** [comment]
Related https://github.com/gazebosim/gz-tools/pull/124
