### ISSUE TITLE
gz-transport: Introduction

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#417]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/transport/13/introduction.html)
- [Source](https://github.com/gazebosim/gz-transport/tree/gz-transport13/tutorials/01_intro.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jmackay2** [comment]
I see no issues with the introduction. 

- [x]  Instructions work
- [x] Images (if there are any) match the result

**Comment by Voldivh** [comment]
Thanks @jmackay2
