### ISSUE TITLE
gz-transport: Logging

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#419]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/transport/13/logging.html)
- [Source](https://github.com/gazebosim/gz-transport/tree/gz-transport13/tutorials/10_logging.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jmackay2** [comment]
I had no issues following the logging tutorial. 

- [x] Instructions work

**Comment by Voldivh** [comment]
Thanks @jmackay2 closing this as completed.
