### ISSUE TITLE
gz-transport: Messages

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#422]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/api/transport/13/messages.html)
- [Source](https://github.com/gazebosim/gz-transport/tree/gz-transport13/tutorials/04_messages.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by caguero** [comment]
Works for me. Some examples links needed to be updated.

https://github.com/gazebosim/gz-transport/pull/439
