### ISSUE TITLE
gz-transport: Nodes and Topics

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#423]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/transport/13/nodestopics.html)
- [Source](https://github.com/gazebosim/gz-transport/tree/gz-transport13/tutorials/03_nodesAndTopics.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jmackay2** [comment]
I didn't see any issues with the Nodes and Topics for gz-transport.

There is a little repetition describing what is valid for topics and namespaces, but better be repetitive than unclear.

- [x] Instructions work
- [x] Images (if there are any) match the result

**Comment by Voldivh** [comment]
Thanks @jmackay2
