### ISSUE TITLE
gz-transport: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#425]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/libs/transport)
- [Source](https://github.com/gazebosim/gz-transport/blob/gz-transport13/README.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Same as issue #426

**Comment by Voldivh** [comment]
Related https://github.com/gazebosim/gz-transport/pull/437
