### ISSUE TITLE
gz-utils: Installation

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#435]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/utils/2/install.html)
- [Source](https://github.com/gazebosim/gz-utils/tree/gz-utils2/tutorials/installation.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by mjcarroll** [comment]
https://github.com/gazebosim/gz-utils/pull/104

**Comment by mjcarroll** [comment]
Everything else good now that instructions have been tidied
