### ISSUE TITLE
gz-utils: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#437]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/libs/utils)
- [Source](https://github.com/gazebosim/gz-utils/blob/gz-utils2/README.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
https://github.com/gazebosim/gz-utils/pull/103
