### ISSUE TITLE
gz-utils: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#438]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/libs/utils)
- [Source](https://github.com/gazebosim/gz-utils/blob/gz-utils2/README.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
Hey, I would like to work on this

**Comment by Kartik9250** [comment]
I was going through the instructions.
 - The documentation generation works fine.
    ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/61a9df00-d43f-419e-b74d-ddd59afb0998)
    Though these warnings show up:
         ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/689f5d08-f414-4a7a-b1bd-615d8ab566b4)


 - I am unable to install from source. I also found the code snippets are not loading properly
   ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/d06e79e8-59d5-4303-a986-20887950cb42)
   ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/a262c5c2-ed4b-40ec-b3c4-973fe3026133)

**Comment by Voldivh** [comment]
Thanks @Kartik9250, I'll take a look into the problems.

**Comment by mjcarroll** [comment]
> I am unable to install from source. I also found the code snippets are not loading properly

Were these code snippets from a doxygen generation that you did or from the website?

**Comment by azeey** [comment]
It seems like the issue is with the doxygen rendering.  This is how that instruction is rendered on my system:
![image](https://github.com/gazebosim/gazebo_test_cases/assets/206116/d328a8a2-f092-44e2-a9af-c711655a6db8)

Can you verify you have doxygen 1.9.1? Run `apt-cache policy doxygen`
