### ISSUE TITLE
sdf_tutorials: Collisions and Visuals

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#440]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](http://sdformat.org/tutorials?tut=spec_shapes)
- [Source](https://github.com/gazebosim/sdf_tutorials/blob/master/spec_shapes/tutorial.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
As mentioned in:
https://github.com/gazebosim/gazebo_test_cases/issues/462#issuecomment-1709946449
https://github.com/gazebosim/gazebo_test_cases/issues/445#issuecomment-1703815390

While I was trying different geometry shapes I found that objects were rendering as black by default, I think its white or grey by default in other versions.
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/65343816-2862-4d13-960c-7bb559cb3286)

Also in the documention the image shows the object in grey:
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/db0b3c6a-134c-40ab-8030-2b5e5ac5f63e)


Geometry, Collision, material are working alright just one issue I found was that the objects were rendering in black by default.

**Comment by Voldivh** [comment]
Thanks @Kartik9250, I'll take note of the issue. Closing this for now.
