### ISSUE TITLE
sdf_tutorials: Creating Worlds

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#445]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](http://sdformat.org/tutorials?tut=spec_world)
- [Source](https://github.com/gazebosim/sdf_tutorials/blob/master/spec_world/tutorial1.md)

## Checks
- [ ] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
Upon opening the SDF provided under the heading **Creating a box and a sphere on ground plane** in Gazebo Harmonic. The elements appear black in color.  However the box and sphere are present in the world
![create_world](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/a38c2307-ebdc-4b1b-a195-5f8db38b3b67)
