### ISSUE TITLE
sdf_tutorials: Install

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#448]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](http://sdformat.org/tutorials?tut=install)
- [Source](https://github.com/gazebosim/sdf_tutorials/blob/master/install/tutorial_12.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
Hey, I would like to work on this

**Comment by Kartik9250** [comment]
Everything works, sdformat was installed successfully
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/c1e07405-0fa2-461d-99e0-ed3d455ee99b)

**Comment by Voldivh** [comment]
Thanks @Kartik9250, closing this as completed
