### ISSUE TITLE
gz-common: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#45]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/libs/common)
- [Source](https://github.com/gazebosim/gz-common/blob/gz-common5/README.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
https://github.com/gazebosim/gz-common/pull/534
