### ISSUE TITLE
sdf_tutorials: Interoperability with other modeling formats

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#450]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](http://sdformat.org/tutorials?tut=interoperability_formats)
- [Source](https://github.com/gazebosim/sdf_tutorials/blob/master/interoperability_formats/tutorial.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by AndrejOrsula** [comment]
https://github.com/gazebosim/sdf_tutorials/pull/96

**Comment by Voldivh** [comment]
PR have been merged, I'll be closing this issue. Thanks @AndrejOrsula
