### ISSUE TITLE
sdf_tutorials: Quickstart

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#457]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](http://sdformat.org/tutorials?tut=quickstart)
- [Source](https://github.com/gazebosim/sdf_tutorials/blob/master/quickstart/tutorial_2-0.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The instructions were found to be working. Attaching screenshot

![parseSDF](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/c9234cac-337b-4852-9ee4-f4484fc42b70)

**Comment by Voldivh** [comment]
Thanks for addressing this @JACOBIN-SCTCS closing it as completed!
