### ISSUE TITLE
sdf_tutorials: Specifying pose

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#461]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](http://sdformat.org/tutorials?tut=specify_pose)
- [Source](https://github.com/gazebosim/sdf_tutorials/blob/master/specify_pose/tutorial.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment]
I'm not quite sure on what to test here... What I did just to make sure that the pose of the model on the sdf was working was to change xyz and rpy in the default `shapes.sdf` and to verify if the changes make sense. All seems to be ok. Here is a screenshot of the altered shapes sdf.

![image](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/48837df7-84cf-4705-8fb5-45ec9b747ea5)

**Comment by Voldivh** [comment]
Thanks @matosinho, since to be correct the output for me.

**Comment by azeey** [comment]
Hi @matosinho, congratulations! You are one of our top contributors in the Harmonic tutorial party. Can you send your email address to `addisu@openrobotics.org`  so we can send you the Harmonic t-shirt?

**Comment by azeey** [comment]
> Hi @matosinho, congratulations! You are one of our top contributors in the Harmonic tutorial party. Can you send your email address to `addisu@openrobotics.org`  so we can send you the Harmonic t-shirt?



Hi @matosinho, I don't think I ever received your email. If you're still interested in getting a Harmonic t-shirt, please email me
