### ISSUE TITLE
sdf_tutorials: Specifying pose

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#462]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](http://sdformat.org/tutorials?tut=specify_pose)
- [Source](https://github.com/gazebosim/sdf_tutorials/blob/master/specify_pose/tutorial.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
Hey, I would like to work on this ticket

**Comment by Kartik9250** [comment]
Hey the pose tag is working fine.
I tried moving a cube on mutliple axis:
- Default:
    ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/e2a2bfa4-4696-41a7-b2e0-42a300d0ad17)

- On Y-Axis:
    ![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/1b062d30-f9d5-42a6-9451-a48303a5a7a1)

Translation on other axis also worked fine.

**Comment by Kartik9250** [comment]
I had to specify material, by default it was showing it as a black box

**Comment by azeey** [comment]
Hi @Kartik9250, congratulations! You are one of our top contributors in the Harmonic tutorial party. Can you send your email address to `addisu@openrobotics.org`  so we can send you the Harmonic t-shirt?

**Comment by Kartik9250** [comment]
> Hi @Kartik9250, congratulations! You are one of our top contributors in the Harmonic tutorial party. Can you send your email address to `addisu@openrobotics.org` so we can send you the Harmonic t-shirt?

@azeey i have sent the email
