### ISSUE TITLE
sdformat: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#465]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/libs/sdformat)
- [Source](https://github.com/gazebosim/sdformat/blob/sdf14/README.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The sequence of steps for the binary installation was found to be working for Ubuntu Jammy (Enclosing screenshot).  The command to clone the required repository I believe is missing in the Unix subsection of Source installa
![SDFormat](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/5665a37f-1f46-4133-a016-d0f36b804e0f)
tion section

**Comment by Voldivh** [comment]
Thanks for addressing this @JACOBIN-SCTCS! 
Would you mind making a comment regarding the missing command on the issue for Source Installation?
