### ISSUE TITLE
sdformat: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#466]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/libs/sdformat)
- [Source](https://github.com/gazebosim/sdformat/blob/sdf14/README.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The command 
```
git clone https://github.com/gazebosim/sdformat -b sdf<#>
cd sdformat
```
is missing from the Source Installation section for Unix. The same command however is present for MacOS based installation

**Comment by Voldivh** [comment]
Thanks for testing it out and noticing the missing steps. I'll create the relevant issue to fix it on the appropriate repository.

**Comment by azeey** [comment]
Hi @JACOBIN-SCTCS, congratulations! You are one of our top contributors in the Harmonic tutorial party. Can you send your email address to `addisu@openrobotics.org`  so we can send you the Harmonic t-shirt?
