### ISSUE TITLE
docs: building_robot

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#5]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/building_robot)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/building_robot.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by suresh-venkate** [comment]
Confirming that I was able to build and view the sdf world in gazebo as per the instructions.

Setup
-------------------------
Os: Ubuntu Jammy
Build Type: Binary

Links Used
-----------------------
[https://gazebosim.org/docs/harmonic/building_robot](url)

![image](https://github.com/gazebosim/gazebo_test_cases/assets/76463566/d88223b4-1f64-4f46-9431-e945b6189906)

**Comment by Voldivh** [comment]
Thanks for addressing this @suresh-venkate !
