### ISSUE TITLE
gz-fuel-tools: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#55]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](https://gazebosim.org/libs/fuel_tools)
- [Source](https://github.com/gazebosim/gz-fuel-tools/blob/gz-fuel-tools9/README.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
https://github.com/gazebosim/gz-fuel-tools/pull/371
