### ISSUE TITLE
gz-math: Color example

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#86]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/api/math/7/color.html)
- [Source](https://github.com/gazebosim/gz-math/tree/gz-math7/tutorials/color.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
Related https://github.com/gazebosim/gz-math/pull/557
