### ISSUE TITLE
docs: GUI_tutorial

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#9]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/gui)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/GUI_tutorial.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The live link is not working in this issue.

**Comment by Voldivh** [comment]
@JACOBIN-SCTCS It should be working now, let me know if you encounter any other trouble.

**Comment by ahcorde** [comment]
updated capture to include reset button https://github.com/gazebosim/docs/pull/383
