### ISSUE TITLE
gz-math: README

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#92]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/libs/math)
- [Source](https://github.com/gazebosim/gz-math/blob/gz-math7/README.md)

## Checks
- [ ] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by ahcorde** [comment]
Related https://github.com/gazebosim/gz-math/pull/556
